unit ServiceIngresos_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

{$I Remobjects.inc}

interface

uses
  {vcl:} Classes, SysUtils, ShlObj, Forms,
  {RemObjects:} uROXMLIntf, uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Required:} uRORemoteDataModule, uDAInterfaces, uDADataStreamer,
  {Ancestor Implementation:} DataAbstractService_Impl,
  {Used RODLs:} DataAbstract4_Intf,
  {Generated:} LibraryIngresos_Intf, uDABin2DataStreamer, uDAScriptingProvider,
  uDABusinessProcessor, uDAClasses,
  {FACTURAELECT}EcodexWsCancelacion, PACComercioDigital, ClaseCertificadoSellos,
  FEImpuestosLocales, ManejadorDeErroresComunes, EcodexWsComun, EcodexWsClientes,
  CadenaOriginalTimbre, FECancelaComercioDigital, QuricolCode, QuricolAPI, GeneradorCBB,
  FacturacionHashes, PAC.Ecodex.ManejadorDeSesion, EcodexWsSeguridad, EcodexWsTimbrado,
  FeCFD, ProveedorAutorizadoCertificacion, FETimbreFiscalDigital, FeCFDv32, FeCFDv2,
  FeCFDv22, CadenaOriginal, DocComprobanteFiscal, DateUtils, SelloDigital, OpenSSLUtils,
  LibEay32Plus, libeay32, FacturaTipos, FacturaReglamentacion, FacturaElectronica,
  ComprobanteFiscal, ClaseOpenSSL, PACEcodex,
  uROClient, uROComponent, uDAStreamableComponent, uDASchema;

type
  { TServiceIngresos }
  TServiceIngresos = class(TDataAbstractService, IServiceIngresos)
    bpReporte: TDABusinessProcessor;
    DataStreamer: TDABin2DataStreamer;
    Schema: TDASchema;
  private
    function IEPS(ProductoID: Integer): Real;
    procedure CalculaIEPS(var Datos: TDatosFactura);

    //function cfd(const FacturaID: Integer; const NumeroEstacion: Integer):  TXmlCFD;
    //function cfdi(const FacturaID: Integer; const NumeroEstacion: Integer): TXmlCFD;
  protected
    { IServiceIngresos methods }
    function AbreDataSetReportes(const SQL: AnsiString; const Parametros: TParametrosBI): Binary;
    function AbreTurno(const IDTURNO: Integer; const IDESTACION: Integer; const FECHA: DateTime): AnsiString;
    function BuscarReporte(const Nombre: AnsiString): TReporteBI;
    function DragPagoMateria(const PAGOMATERIA: Integer; const IDGRUPOTARGET: Integer; const IDGRUPOSOURCE: Integer): Boolean;
    function ActualizaSubTipoPago(const IDTIPOPAGO: Integer; const IDSUBTIPOPAGO: Integer): Boolean;
    function DatosFacturaElectronica(const FacturaID: Integer; const NumeroEstacion: Integer): TFacturaElectronicaBI;
    function DatosFactura(const Folio: Integer; const Serie: AnsiString): Boolean;
    function Fecha: DateTime;
    function Folio(const Campo: AnsiString; const Serie: AnsiString): Integer;
    procedure GuardaDatosFactura(const DatosFactura: TDatosFactura);
    function Login(const Usuario: AnsiString; const Clave: AnsiString): TLoginInfoBI;
    function IniciaCiclo(const IDCICLO: AnsiString): Boolean;
    function ModificarFolioActual(const Campo: AnsiString; const Serie: AnsiString; const FolioNew: Integer): AnsiString;
    procedure InsertaFacturaElectronica(const FacturaElectronicaID: Integer; const CadenaOriginal: UnicodeString; const SelloDigital: UnicodeString;
                                        const FacturaID: Integer; const Vigencia: Boolean; const Enviado: Boolean; const NoCertificado: AnsiString;
                                        const NoAprobacion: AnsiString; const FechaAprobacion: DateTime; const XMLCFD: UnicodeString; const XMLCFDI: UnicodeString);
    function FolioActual2(const Serie: AnsiString; const folio: Integer): Integer;
    procedure GuardaAccesos(const UsuarioID: Integer; const Lista: AnsiString);
    function EliminaMaestroDisponibilidad(const IDMAESTRODISPONIBILIDAD: Integer): Boolean;
    function EliminaMateriaMaestro(const IDMAESTRO: Integer; const IDMATERIA: Integer): Boolean;
    function EliminaPago(const idSubtipoPago: Integer; const status: AnsiString; const idCiclos: Integer; const idGrupo: Integer): Boolean;
    function EliminaPagoCaja(const idSubtipoPago: Integer; const status: AnsiString; const idCiclos: Integer; const idGrupo: Integer): Boolean;
    function InsertaCaja(const Observaciones: AnsiString; const TipoPago: AnsiString; const idEmpleado: Integer): Integer;
    function LiquidaPago(const INTERES: Double; const IDEMPLEADO: Integer; const IDPAGO: Integer): Boolean;
    function DividePago(const idPago: Integer; const idEmpleado: Integer; const Importes: Double; const Interes: Double): Integer;
    function InsertaPagoCaja(const IDPAGO: Integer; const IDCAJA: Integer): Boolean;
    function AplicaCalificacion(const Calificacion: Double; const Faltas: Integer; const idmaterias: Integer; const idhistorialalumno: Integer;
                                const idhistorialgrupo: Integer; const fecha: DateTime; const idtipocalificacion: Integer; const califAux2: Double;
                                const califAux1: Double): Boolean;
    function HistorialAlumnoDEL(const IDHISTORIALALUMNO: Integer): Boolean;
    function BecaDescuento(const IDHISTORIALALUMNO: Integer; const BECA: Double; const DESCUENTO: Double): Boolean;
    function InsertaHistorialAlumno(const IDHISTORIALALUMNO: Integer; const IDHISTORIALGRUPO: Integer; const IDALUMNO: Integer; const DOCUMENTOSFALTANTES: AnsiString;
                                    const BECA: Double; const DESCUENTO: Double): Boolean;
    function CambioGrupo(const IDHISTORIALALUMNO: Integer; const IDHISTORIALGRUPO: Integer; const DOCUMENTOSFALTANTES: AnsiString;
                         const BECA: Double; const DESCUENTO: Double): Boolean;
    function TipoCalificacion: Integer;
    function DatosAlumno(const AlumnoID: Integer): TDatos;
    function DatosMaestro(const MaestroID: Integer): TDatos;
    function PagoBanco(const FECHAPAGO: DateTime; const IDEMPLEADO: Integer; const IDPAGO: Integer; const MONTO: Double): Integer;
    function PrecioProducto(const ProductoID: Integer): Double;
    function FolioActual(const Campo: AnsiString; const Serie: AnsiString): Integer;
    function ValidaFolioFactura(const Campo: AnsiString; const Folio: Integer): Boolean;
    function GuardarDatosFactura(const DatosFactura: TDatosFactura): AnsiString;
    function ActualizaTipoCampio(const NUMEROESTACION: Int64; const FECHA: DateTime; const VALOR: Double; const IDMONEDA: Integer): Boolean;
    function ObtenTipoValores(const NUMEROESTACION: Integer; const FECHA: DateTime): ATTipoValores;
    function CostoProducto(const IDPRODUCTO: Integer): Double;
    function Exporta(const ExportarID: Integer): TExporta;
    function ObtenTurnosdeFecha(const Fecha: DateTime; const Estacion: Integer): ATTurnoxFecha;
    function CierraLiquidacion(const LiquidacionID: Integer): AnsiString;
  end;

implementation

{$R *.dfm}
uses
  {Generated:} LibraryIngresos_Invk, UtileriasComun, fServerDataModule;

function GetDesktopFolder: string;
var
     buf: array[0..255] of char;
     pidList: PItemIDList;
begin
     Result := 'No Desktop Folder found.';
     SHGetSpecialFolderLocation(Application.Handle, CSIDL_DESKTOP, pidList);
     if (pidList <> nil) then
      if (SHGetPathFromIDList(pidList, buf)) then
        Result := buf;
end;

procedure Create_ServiceIngresos(out anInstance : IUnknown);
begin
  anInstance := TServiceIngresos.Create(nil);
end;

{ ServiceIngresos }
function TServiceIngresos.AbreDataSetReportes(const SQL: AnsiString; const Parametros: TParametrosBI): Binary;
var
  DataSet: IDADataset;
  Aux: TStrings;
procedure AgregaParametro(Nombre: String; Tipo: TDADataType);
begin
  with DataSet.Params.Add do
  begin
    Name:=Nombre;
    DataType:=Tipo;
  end;    // with
end;
begin
  Aux:=TStringList.Create;
  if  FileExists('DefaultServerIngresos.dat') then
    Aux.LoadFromFile('DefaultServerIngresos.dat');
  DataSet := Connection.NewDataset(Aux.Text + SQL, 'Reporte');
  Aux.Add(SQL);
  Aux.SaveToFile('SQL.txt');
  Aux.Free;
  AgregaParametro('FechaIni', datDateTime);
  AgregaParametro('FechaFin', datDateTime);
  AgregaParametro('Alumno', datInteger);
  AgregaParametro('AlumnoIni', datInteger);
  AgregaParametro('AlumnoFin', datInteger);
  AgregaParametro('Grupo', datInteger);
  AgregaParametro('Ciclo', datInteger);
  AgregaParametro('Maestro', datInteger);
  AgregaParametro('MaestroIni', datInteger);
  AgregaParametro('MaestroFin', datInteger);
  AgregaParametro('Nivel', datInteger);
  AgregaParametro('TipoPago', datInteger);
  AgregaParametro('TipoCalificacion', datInteger);
  AgregaParametro('Usuario', datInteger);
  AgregaParametro('Familia', datInteger);
  AgregaParametro('Valor1', datString);
  AgregaParametro('Status', datInteger);
  AgregaParametro('Serie', datString);
  AgregaParametro('Factura', datInteger);
  AgregaParametro('FacturasCompras', datInteger);
  AgregaParametro('TurnoInicio', datInteger);
  AgregaParametro('TurnoFin', datInteger);
  AgregaParametro('NumeroEstacion', datInteger);
  AgregaParametro('HorarioIni', datInteger);
  AgregaParametro('HorarioFin', datInteger);
  AgregaParametro('NumeroEstacionIni', datInteger);
  AgregaParametro('NumeroEstacionFin', datInteger);

  //DataSet.ParamByName('ProcesaTabla').AsInteger:=Byte(Pos('#CONSUMOS', UpperCase(SQL)) > 0);

  DataSet.ParamByName('FechaIni').AsDateTime:=Parametros.FechaIni;
  DataSet.ParamByName('FechaFin').AsDateTime:=Parametros.FechaFin;
  DataSet.ParamByName('Alumno').AsInteger:=Parametros.Alumno;
  DataSet.ParamByName('AlumnoIni').AsInteger:=Parametros.AlumnoIni;
  DataSet.ParamByName('AlumnoFin').AsInteger:=Parametros.AlumnoFin;
  DataSet.ParamByName('Grupo').AsInteger:=Parametros.Grupo;
  DataSet.ParamByName('Ciclo').AsInteger:=Parametros.Ciclo;
  DataSet.ParamByName('Maestro').AsInteger:=Parametros.Maestro;
  DataSet.ParamByName('MaestroIni').AsInteger:=Parametros.MaestroIni;
  DataSet.ParamByName('MaestroFin').AsInteger:=Parametros.MaestroFin;
  DataSet.ParamByName('Nivel').AsInteger:=Parametros.Nivel;
  DataSet.ParamByName('TipoPago').AsInteger:=Parametros.TipoPago;
  DataSet.ParamByName('TipoCalificacion').AsInteger:=Parametros.TipoCalificacion;
  DataSet.ParamByName('Usuario').AsInteger:=Parametros.Usuario;
  DataSet.ParamByName('Familia').AsInteger:=Parametros.Familia;
  DataSet.ParamByName('Valor1').AsInteger:=Parametros.Valor1;
  DataSet.ParamByName('Status').AsInteger:=Parametros.Status;
  DataSet.ParamByName('Serie').AsString:=Parametros.Serie;
  DataSet.ParamByName('Factura').AsInteger:= Parametros.Factura;
  DataSet.ParamByName('FacturasCompras').AsInteger:= Parametros.FacturasCompras;
  DataSet.ParamByName('TurnoInicio').AsInteger:= Parametros.TurnoInicio;
  DataSet.ParamByName('TurnoFin').AsInteger:= Parametros.TurnoFin;
  DataSet.ParamByName('NumeroEstacion').AsInteger:= Parametros.NumeroEstacion;
  DataSet.ParamByName('HorarioIni').AsInteger:= Parametros.HorarioIni;
  DataSet.ParamByName('HorarioFin').AsInteger:= Parametros.HorarioFin;
  DataSet.ParamByName('NumeroEstacionIni').AsInteger:= Parametros.NumeroEstacionIni;
  DataSet.ParamByName('NumeroEstacionFin').AsInteger:= Parametros.NumeroEstacionFin;

  DataSet.Open;
  Result := Binary.Create;
  DataStreamer.WriteDataset(result, DataSet, [woSchema, woRows]);
  DataSet.Close;
end;

function TServiceIngresos.BuscarReporte(const Nombre: AnsiString): TReporteBI;
var
  MiDataSet: IDADataSet;
begin
  Result:=nil;
  MiDataSet:=Schema.NewDataset(Connection, 'BuscarReporte');
  MiDataSet.ParamByName('Nombre').AsString:=UpperCase(Nombre);
  MiDataSet.Open;
  if not MiDataSet.IsEmpty then
  begin
    Result:=TReporteBI.Create;
    Result.SQL1:=MiDataSet.FieldByName('SQL1').AsString;
    Result.SQL2:=MiDataSet.FieldByName('SQL2').AsString;
    Result.Template:=MiDataSet.FieldByName('Template').AsString;
    Result.CampoJoin:=MiDataSet.FieldByName('CampoJoin').AsString;
  end;
  MiDataSet.Close;
end;

function TServiceIngresos.DragPagoMateria(const PAGOMATERIA: Integer; const IDGRUPOTARGET: Integer; const IDGRUPOSOURCE: Integer): Boolean;
begin
end;

function TServiceIngresos.ActualizaSubTipoPago(const IDTIPOPAGO: Integer; const IDSUBTIPOPAGO: Integer): Boolean;
begin
end;

function TServiceIngresos.ActualizaTipoCampio(const NUMEROESTACION: Int64;
  const FECHA: DateTime; const VALOR: Double; const IDMONEDA: Integer): Boolean;
var
  cmd:IDASQLCommand;
begin
  Result:= False;
  cmd:=Schema.NewCommand(Connection, 'ActualizaTipoCambio');
  cmd.ParamByName('IDVALORMONEDA').AsInteger:= Folio('IDVALORMONEDA','');
  cmd.ParamByName('IDMONEDA').AsInteger:= IDMONEDA;
  cmd.ParamByName('VALOR').AsFloat:= VALOR;
  cmd.ParamByName('NUMEROESTACION').AsInteger:= NUMEROESTACION;
  cmd.ParamByName('FECHA').AsDateTime:= FECHA;

  cmd.Execute;
  Result:= True;
end;

function TServiceIngresos.DatosFacturaElectronica(const FacturaID: Integer; const NumeroEstacion: Integer): TFacturaElectronicaBI;
var
  ds1: IDADataSet;
  ds2: IDADataSet;
  ds3: IDADataSet;
  ds4: IDADataSet;
  ds5: IDADataSet;

  TOTImpuestos: Double;
begin
  /////
  Result:=TFacturaElectronicaBI.Create();

  TOTImpuestos:=0;

  ds1:=Schema.NewDataset(Connection, 'spDatosCadena');
  ds1.ParamByName('FacturaID').AsInteger:=FacturaID;
  ds1.ParamByName('NUMEROESTACION').AsInteger:= NumeroEstacion;

  ds1.Open;

  ds5:=Schema.NewDataset(Connection, 'spDatosCadenaExpedidoEn');
  ds5.ParamByName('NUMEROESTACION').AsInteger:= NumeroEstacion;
  ds5.Open;

  while not (ds1.EOF) do
  begin

    if not(ds5.EOF) then
    begin
      Result.CalleExpedidoEn:= ds5.FieldByName('Domicilio').AsString;
      Result.NoExterioExpedidoEn:= ds5.FieldByName('NoExterior').AsString;
      Result.ColoniaExpedidoEn:= ds5.FieldByName('Colonia').AsString;
      Result.CodigoPostalExpedidoEn:= ds5.FieldByName('CodigoPostal').AsString;
      Result.LocalidadExpedidoEn:= ds5.FieldByName('Localidad').AsString;
      Result.MunicipioExpedidoEn:= ds5.FieldByName('Municipio').AsString;
      Result.EstadoExpedidoEn:= ds5.FieldByName('Estado').AsString;
      Result.PaisExpedidoEn:= ds5.FieldByName('Pais').AsString;
      Result.Sucursal:= ds5.FieldByName('Sucursal').AsBoolean;
    end else Result.Sucursal:= False;
    

    Result.Serie:= ds1.FieldByName('SERIE').AsString;
    Result.Folio:= ds1.FieldByName('FOLIO').AsString;
    Result.Fecha:= ds1.FieldByName('FECHA').AsString;
    Result.noAprobacion:= ds1.FieldByName('NOAPROBACION').AsString;
    Result.anoAprobacion:= ds1.FieldByName('ANOAPROBACION').AsString;
    Result.tipoComprobante:= ds1.FieldByName('FORMAPAGO').AsString;
    Result.formaDePago:= 'pago en una sola exhibicion';
    Result.SubTotal:= ds1.FieldByName('SUBTOTAL').AsString;
    Result.Total:= ds1.FieldByName('TOTAL').AsString;
    Result.RFCEmisor:= ds1.FieldByName('RFCEMISOR').AsString;
    Result.NOMEmpEmisor:= ds1.FieldByName('NOMEMPRESAEMISOR').AsString;
    Result.DireccionEm:= ds1.FieldByName('DOMEMISOR').AsString;
    Result.NOExteriorEM:= ds1.FieldByName('NOEXTERIOREMISOR').AsString;
    Result.ColoniaEmisor:= ds1.FieldByName('COLONIAEMISOR').AsString;
    Result.MunicipioEmisor:= ds1.FieldByName('MUNICIPIOEMISOR').AsString;
    Result.EstadoEmisor:= ds1.FieldByName('ESTADOEMISOR').AsString;
    Result.PaisEmisor:= ds1.FieldByName('PAISEMISOR').AsString;
    Result.CodigoPostalEmisor:= ds1.FieldByName('CODIGOPOSTALEMISOR').AsString;

    Result.RFCReceptor:= ds1.FieldByName('RFCRECEPTOR').AsString;
    Result.NombreReceptor:= ds1.FieldByName('NOMBREEMPRECEPTOR').AsString;
    Result.DomicilioReceptor:= ds1.FieldByName('DOMICILIORECEPTOR').AsString;
    Result.NoExteriorReceptor:= ds1.FieldByName('NOEXTERIORRECEPTOR').AsString;
    Result.ColoniaReceptor:= ds1.FieldByName('COLONIARECEPTOR').AsString;
    Result.LocalidadReceptor:= ds1.FieldByName('LOCALIDADRECEPTOR').AsString;
    Result.MunicipioReceptor:= ds1.FieldByName('MUNICIPIORECEPTOR').AsString;
    Result.EstadoReceptor:= ds1.FieldByName('ESTADORECEPTOR').AsString;
    Result.PaisReceptor:= ds1.FieldByName('PAISRECEPTOR').AsString;
    Result.CodigoPostalReceptor:= ds1.FieldByName('CODIGOPOSTALRECEPTOR').AsString;
    Result.email:= ds1.FieldByName('email').AsString;
    ds1.Next;
  end;

  ds2:=Schema.NewDataset(Connection, 'spDatosCadenaImportes');
  ds2.ParamByName('FacturaID').AsInteger:=FacturaID;
  ds2.Open;

  while not (ds2.EOF) do
  begin
    With Result.FacturaElectronicaDetalleImportes.Add do begin
      if ds2.FieldByName('ProductoID').AsInteger <= 3 then
         UnidadReceptor:= 'LTS'
      else
         UnidadReceptor:= 'UNI';

      CantidadReceptor:= FormatFloat('###0.00',(ds2.FieldByName('IMPORTE').AsFloat/
      strtofloat(FormatFloat('###0.00',ds2.FieldByName('PRECIO').AsFloat))));

      DescripcionReceptor:= ds2.FieldByName('DESCRIPCION').AsString;
      ValorUnitarioReceptor:= FormatFloat('###0.00',ds2.FieldByName('PRECIO').AsFloat);
      ImporteReceptor:= FormatFloat('###0.00',ds2.FieldByName('IMPORTE').AsFloat);
    end;
    ds2.Next;
  end;

      ds3:=Schema.NewDataset(Connection, 'spDatosCadenaImpuestosIEPS');
      ds3.ParamByName('FacturaID').AsInteger:=FacturaID;
      ds3.Open;

      ds4:=Schema.NewDataset(Connection, 'spDatosCadenaImpuestosIVA');
      ds4.ParamByName('FacturaID').AsInteger:=FacturaID;
      ds4.Open;

      while not (ds3.EOF) do
      begin
        if ds3.FieldByName('IEPS').AsFloat <> 0 then
        begin
           With Result.FacturaElectronicaDetalleImpuestos.Add do
           begin
                ImporteImpReceptor:= FormatFloat('###0.00',ds3.FieldByName('IEPS').AsFloat);
                TasaReceptor:= FormatFloat('###0.0000',ds3.FieldByName('TASAIEPS').AsFloat);
                ImpuestoReceptor:= 'IEPS';
                TOTImpuestos:= TOTImpuestos + ds3.FieldByName('IEPS').AsFloat;
                ds3.Next;
           end;
        end else ds3.Next;
      end;

      while not (ds4.EOF) do
      begin
        if ds4.FieldByName('IVA').AsFloat <> 0 then
        begin
           With Result.FacturaElectronicaDetalleImpuestos.Add do
           begin
                ImporteImpReceptor:= FormatFloat('###0.00',ds4.FieldByName('IVA').AsFloat);
                TasaReceptor:= FormatFloat('###0.0000',ds4.FieldByName('TASAIVA').AsFloat);
                ImpuestoReceptor:= 'IVA';
                TOTImpuestos:= TOTImpuestos + ds4.FieldByName('IVA').AsFloat;
               ds4.Next;
           end;
        end else ds4.Next;
      end;

  Result.TotalImpuesto:= FormatFloat('###0.0000',TOTImpuestos);
end;

function TServiceIngresos.DatosFactura(const Folio: Integer; const Serie: AnsiString): Boolean;
begin
end;

function TServiceIngresos.Fecha: DateTime;
begin
  Result:=Now;
end;

function TServiceIngresos.Folio(const Campo: AnsiString; const Serie: AnsiString): Integer;
var
  DataSet: IDADataset;
begin
  DataSet:=Schema.NewDataset(Connection, 'spFolio');
  DataSet.ParamByName('Campo').AsString:=Campo;
  DataSet.ParamByName('Serie').AsString:=Serie;
  DataSet.Open;
  Result:=DataSet.FieldByName('Folio').AsInteger;
  DataSet.Close;
end;

procedure TServiceIngresos.GuardaDatosFactura(const DatosFactura: TDatosFactura);
begin
end;

function TServiceIngresos.Login(const Usuario: AnsiString; const Clave: AnsiString): TLoginInfoBI;
var
  DataSet, Permisos: IDADataSet;
begin
  Result:=TLoginInfoBI.Create;
  DataSet:=Schema.NewDataset(Connection, 'spValidaUsuario');
  DataSet.ParamByName('Usuario').AsString:=Usuario;
  DataSet.ParamByName('Clave').AsString:=Clave;
  DataSet.Open;
  if not DataSet.IsEmpty then
  begin
    Result.Valida:=True;
    Result.EmpleadoID:=DataSet.FieldByName('IDEMPLEADO').AsInteger;
    Result.NombreEmpleado:=DataSet.FieldByName('Nombre').AsString;
    Permisos:=Schema.NewDataset(Connection, 'spAccesos');
    Permisos.ParamByName('UsuarioID').AsInteger:=Result.EmpleadoID;
    Permisos.Open;
    while not Permisos.EOF do
    begin
      with Result.Accesos.Add do
      begin
        OpcionID:=Permisos.FieldByName('OpcionID').AsInteger;
        Nombre:=Permisos.FieldByName('Descripcion').AsString;
      end;
      Permisos.Next;
    end;
    Permisos.Close;
  end
  else
  begin
    Result.Valida:=False;
    Result.EmpleadoID:=0;
    Result.NombreEmpleado:='';
  end;
  DataSet.Close;
end;

function TServiceIngresos.IEPS(ProductoID: Integer): Real;
var
  ds: IDADataset;
begin
  ds:=Schema.NewDataset(Connection, 'spIEPS');
  ds.ParamByName('ProductoID').AsInteger:=ProductoID;
  ds.Open;
  Result:=Decimales(ds.FieldByName('IEPS').AsFloat, 4);
  ds.Close;
end;

function TServiceIngresos.IniciaCiclo(const IDCICLO: AnsiString): Boolean;
begin
end;

function TServiceIngresos.ModificarFolioActual(const Campo: AnsiString; const Serie: AnsiString; const FolioNew: Integer): AnsiString;
begin
end;

function TServiceIngresos.ObtenTipoValores(const NUMEROESTACION: Integer;
  const FECHA: DateTime): ATTipoValores;
var
  ds: IDADataSet;
  ds2:IDADataSet;
begin
  Result:= ATTipoValores.Create;
  try
    ds := Schema.NewDataset(Connection, 'spTipoCambio');
    ds2 := Schema.NewDataset(Connection, 'dbo MONEDA');
    ds2.Open;

    while not ds2.EOF do
    begin
    ds.ParamByName('NUMEROESTACION').AsInteger := NUMEROESTACION;
    ds.ParamByName('FECHA').AsDateTime := FECHA;
    ds.ParamByName('IDMONEDA').AsInteger := ds2.FieldByName('IDMONEDA').AsInteger;
    ds.Open;

    if ds.RecordCount > 0 then
    begin
      with Result.Add do
      begin
      IDMONEDA:= ds.FieldByName('IDMONEDA').AsInteger;
      VALOR:= ds.FieldByName('VALOR').AsFloat;
      end;
    end;
    ds2.Next;
    end;
  finally
    ds.Close;
  end;
end;

function TServiceIngresos.ObtenTurnosdeFecha(const Fecha: DateTime;
  const Estacion: Integer): ATTurnoxFecha;
var
  ds: IDADataSet;
begin
  Result:= ATTurnoxFecha.Create;
  try
    ds := Schema.NewDataset(Connection, 'spObtenTurnosdeFecha');

    ds.ParamByName('ESTACION').AsInteger := Estacion;
    ds.ParamByName('FECHA').AsDateTime := FECHA;
    ds.Open;


    while not ds.EOF do
    begin

      with Result.Add do
      begin
        IDTURNO := ds.FieldByName('IDTURNO').AsInteger;
        FECHA   := ds.FieldByName('FECHA').AsDateTime;
        IDHORARIO := ds.FieldByName('IDHORARIO').AsInteger;
      end;

      ds.Next;
    end;
  finally
    ds.Close;
  end;
end;

procedure TServiceIngresos.InsertaFacturaElectronica(const FacturaElectronicaID: Integer; const CadenaOriginal: UnicodeString; const SelloDigital: UnicodeString;
                                        const FacturaID: Integer; const Vigencia: Boolean; const Enviado: Boolean; const NoCertificado: AnsiString;
                                        const NoAprobacion: AnsiString; const FechaAprobacion: DateTime; const XMLCFD: UnicodeString; const XMLCFDI: UnicodeString);
var
  cmd:IDASQLCommand;
begin
  cmd:=Schema.NewCommand(Connection, 'spInsertaFCTELECTRONICA');
  cmd.ParamByName('FacturaElectornicaID').AsInteger:= Folio('FacturaElectronicaID','');
  cmd.ParamByName('CadenaOriginal').AsWideString:= CadenaOriginal;
  cmd.ParamByName('SelloDigital').AsWideString:= SelloDigital;
  cmd.ParamByName('FacturaID').AsInteger:= FacturaID;
  cmd.ParamByName('Vigencia').AsBoolean:= Vigencia;
  cmd.ParamByName('Enviado').AsBoolean:= Enviado;
  cmd.ParamByName('NoCertificado').AsString:= NoCertificado;
  cmd.ParamByName('Noaprobacion').AsString:= NoAprobacion;
  cmd.ParamByName('FechaAprobacion').AsDateTime:= FechaAprobacion;
  cmd.ParamByName('XMLCFD').AsWideString:= XMLCFD;

  cmd.Execute;
end;

function TServiceIngresos.FolioActual2(const Serie: AnsiString; const folio: Integer): Integer;
begin
end;

procedure TServiceIngresos.GuardaAccesos(const UsuarioID: Integer; const Lista: AnsiString);
var
  I: Integer;
  MiLista: TStrings;
  cmdElimina: IDASQLCommand;
  cmdInserta: IDASQLCommand;
begin
  cmdElimina:=Schema.NewCommand(Connection, 'AccesosEliminar');
  cmdElimina.ParamByName('UsuarioID').AsInteger:=UsuarioID;
  cmdElimina.Execute;
  cmdInserta:=Schema.NewCommand(Connection, 'AccesosInsertar');
  cmdInserta.ParamByName('UsuarioID').AsInteger:=UsuarioID;
  MiLista:=TStringList.Create;
  MiLista.Text:=Lista;
  try
    for I := 0 to MiLista.Count - 1 do
    begin
      cmdInserta.ParamByName('OpcionID').AsString:=MiLista[I];
      cmdInserta.Execute;
    end;
  finally
    MiLista.Free;
  end;
end;

function TServiceIngresos.EliminaMaestroDisponibilidad(const IDMAESTRODISPONIBILIDAD: Integer): Boolean;
begin
end;

function TServiceIngresos.EliminaMateriaMaestro(const IDMAESTRO: Integer; const IDMATERIA: Integer): Boolean;
begin
end;

function TServiceIngresos.EliminaPago(const idSubtipoPago: Integer; const status: AnsiString; const idCiclos: Integer; const idGrupo: Integer): Boolean;
begin
end;

function TServiceIngresos.EliminaPagoCaja(const idSubtipoPago: Integer; const status: AnsiString; const idCiclos: Integer; const idGrupo: Integer): Boolean;
begin
end;

function TServiceIngresos.Exporta(const ExportarID: Integer): TExporta;
var
  ds, dsS, dsP, dsE: IDADataset;
begin
  Result:=TExporta.Create;
  Result.Campos:=ACampos.Create;
  Result.Pasos:=APasos.Create;
  dsE:=Schema.NewDataset(Connection, 'spExporta');
  dsE.ParamByName('ExportarID').AsInteger:=ExportarID;
  dsE.Open;
  Result.Template:=dsE.FieldByName('Template').AsString;
  Result.ScriptDatos:=dsE.FieldByName('ScriptDatos').AsString;
  Result.ScriptExporta:=dsE.FieldByName('ScriptExporta').AsString;
  Result.Parametros:=dsE.FieldByName('Parametros').AsString;
  Result.Nombre:=dsE.FieldByName('Nombre').AsString;
  dsE.Close;

  ds:=Schema.NewDataset(Connection, 'spCampos');
  ds.ParamByName('ExportarID').AsInteger:=ExportarID;
  ds.Open;
  while not ds.EOF do
  begin
    with Result.Campos.Add do
    begin
      Nombre:=ds.FieldByName('Nombre').AsString;
      Size:=ds.FieldByName('Size').AsInteger;
      Formato:=ds.FieldByName('Formato').AsString;
      Tipo:=ds.FieldByName('Tipo').AsInteger;
    end;
    ds.Next;
  end;
  ds.Close;

  dsS:=Schema.NewDataset(Connection, 'spServers');
  dsP:=Schema.NewDataset(Connection, 'spPasos');
  dsP.ParamByName('ExportarID').AsInteger:=ExportarID;
  dsP.Open;
  while not dsP.EOF do
  begin
    with Result.Pasos.Add do
    begin
      SQL:=dsP.FieldByName('SQL').AsString;
      Server.Estaciones:=AEstaciones.Create;
      dsS.ParamByName('ServidorID').AsInteger:=dsP.FieldByName('ServidorID').AsInteger;
      dsS.Open;
      while not dsS.EOF do
      begin
        Server.ServidorID:=dsS.FieldByName('ServidorID').AsInteger;
        if dsS.FieldByName('EstacionID').AsInteger = 0 then
          Server.Host:=dsS.FieldByName('HostServidor').AsString
        else
        begin
          with Server.Estaciones.Add do
          begin
            EstacionID:=dsS.FieldByName('EstacionID').AsInteger;
            Host:=dsS.FieldByName('HostEstacion').AsString
          end;
        end;
        dsS.Next;
      end;
      dsS.Close;
    end;
    dsP.Next;
  end;
  dsP.Close;
end;

function TServiceIngresos.InsertaCaja(const Observaciones: AnsiString; const TipoPago: AnsiString; const idEmpleado: Integer): Integer;
begin
end;

function TServiceIngresos.LiquidaPago(const INTERES: Double; const IDEMPLEADO: Integer; const IDPAGO: Integer): Boolean;
begin
end;

function TServiceIngresos.DividePago(const idPago: Integer; const idEmpleado: Integer; const Importes: Double; const Interes: Double): Integer;
begin
end;

function TServiceIngresos.InsertaPagoCaja(const IDPAGO: Integer; const IDCAJA: Integer): Boolean;
begin
end;

function TServiceIngresos.AplicaCalificacion(const Calificacion: Double; const Faltas: Integer; const idmaterias: Integer; const idhistorialalumno: Integer; 
                                             const idhistorialgrupo: Integer; const fecha: DateTime; const idtipocalificacion: Integer; const califAux2: Double; 
                                             const califAux1: Double): Boolean;
begin
end;

function TServiceIngresos.AbreTurno(const IDTURNO: Integer; const IDESTACION: Integer; const FECHA: DateTime): AnsiString;
var
  FOLIOIDINGRESO, FOLIOIDDDETALLEINGRESOS: Integer;
  ds: IDADataset;
  ds1: IDADataset;
  ds2: IDADataset;
begin
  Result:= 'TURNO NO GENERADO';

  FOLIOIDINGRESO:= Folio('IDINGRESO','');
  FOLIOIDDDETALLEINGRESOS:= Folio('IDDDETALLEINGRESOS','');

  ds:=Schema.NewDataset(Connection, 'spAbreTurno');
  ds.ParamByName('IDINGRESO').AsInteger:=FOLIOIDINGRESO;
  ds.ParamByName('FECHA').AsDateTime:=FECHA;
  ds.ParamByName('IDTURNO').AsInteger:=IDTURNO;
  ds.ParamByName('NUMEROESTACION').AsInteger:=IDESTACION;
  ds.Open;

  ds1:= Schema.NewDataset(Connection, 'AGRUPACION');
  ds1.ParamByName('IDESTACION').AsInteger:= IDESTACION;
  ds1.Open;

  ds2:= Schema.NewDataset(Connection, 'spAbreAgrupaciones');
  ds2.ParamByName('IDINGRESO').AsInteger:= FOLIOIDINGRESO;
  while not (ds1.EOF) do
  begin
    ds2.ParamByName('IDENCARGADOINGRESOS').AsInteger:= Folio('IDENCARGADOINGRESOS','');
    ds2.ParamByName('IDAGRUPACION').AsInteger:= ds1.FieldByName('IDAGRUPACION').AsInteger;
    ds1.Next;
    ds2.Execute;
  end;

  if not (ds.EOF) then
     Result:= ds.FieldByName('RESULT').AsString;

end;

function TServiceIngresos.HistorialAlumnoDEL(const IDHISTORIALALUMNO: Integer): Boolean;
begin
end;

function TServiceIngresos.BecaDescuento(const IDHISTORIALALUMNO: Integer; const BECA: Double; const DESCUENTO: Double): Boolean;
begin
end;

function TServiceIngresos.InsertaHistorialAlumno(const IDHISTORIALALUMNO: Integer; const IDHISTORIALGRUPO: Integer; const IDALUMNO: Integer; const DOCUMENTOSFALTANTES: AnsiString;
                                                 const BECA: Double; const DESCUENTO: Double): Boolean;
begin
end;

function TServiceIngresos.CambioGrupo(const IDHISTORIALALUMNO: Integer; const IDHISTORIALGRUPO: Integer; const DOCUMENTOSFALTANTES: AnsiString;
                                      const BECA: Double; const DESCUENTO: Double): Boolean;
begin
end;

{function TServiceIngresos.cfd(const FacturaID, NumeroEstacion: Integer): TXmlCFD;
var
  CDOR: WideString;
  ind, idx: integer;
  ds1: IDADataSet;

  DatosFCTElectronica: TDataFacturaElectronicaBI;
begin
  ds1:=Schema.NewDataset(Connection, 'spDatosCertificado');
  //ds1.ParamByName('NUMEROESTACION').AsInteger:= NumeroEstacion;
  ds1.Open;

  DatosFCTElectronica:= TDataFacturaElectronicaBI.Create();
  DatosFCTElectronica.FacturaElectronicaBI.Assign(DatosFacturaElectronica(FacturaID,NumeroEstacion));

  Result:= generaCFD(DatosFCTElectronica,
                     ds1.FieldByName('ArchivoCertificado').AsString,
                     ds1.FieldByName('ArchivoClavePrivada').AsString,
                     ds1.FieldByName('PasswordFCTELECT').AsString);
end; }

{function TServiceIngresos.cfdi(const FacturaID,
  NumeroEstacion: Integer): TXmlCFD;
begin

end;}

function TServiceIngresos.CierraLiquidacion(
  const LiquidacionID: Integer): AnsiString;
var
  ds, dsTotalAlmacen: IDADataSet;
  dsInventario: IDADataSet;
  dsFaltantes: IDADataSet;
  MovID, AlmacenID, MiEstacionID: Integer;
  cmdMov, cmdDet, cmdFyP, cmdDetLiq, cmdCierra: IDASQLCommand;
  MiFecha: TDateTime;
begin
  Result:='OK';
  ds:=Schema.NewDataset(Connection, 'spValidaCierreLiquidacion');
  ds.ParamByName('LiquidacionID').AsInteger:=LiquidacionID;
  ds.Open;
  MiEstacionID:=ds.FieldByName('EstacionID').AsInteger;
  MiFecha:=ds.FieldByName('Fecha').AsDateTime;
  if not ds.FieldByName('Existe').AsBoolean then
  begin
    Result:='la liquidación no existe.';
    ds.Close;
    Exit;
  end;

  if ds.FieldByName('Cerrada').AsBoolean then
  begin
    Result:='La liquidación ya está cerrada.';
    ds.Close;
    Exit;
  end;

  if ds.FieldByName('Despachador').AsInteger > 0 then
  begin
    Result:='Debe seleccionar un despachador.';
    ds.Close;
    Exit;
  end;

  dsInventario:=Schema.NewDataset(Connection, 'spInventarioOtrosProductos');
  dsInventario.ParamByName('LiquidacionID').AsInteger:=LiquidacionID;
  dsInventario.Open;

  AlmacenID:=-1;
  MovID:=0;
  cmdMov:=Schema.NewCommand(Connection, 'Insert_dbo MovimientoAlmacen2');
  cmdDet:=Schema.NewCommand(Connection, 'Insert_dbo DetalleMovimientoAlmacen2');
  dsTotalAlmacen:=Schema.NewDataset(Connection, 'spTotalAlmacen');
  while not dsInventario.EOF do
  begin
    if dsInventario.FieldByName('IDAlmacen').AsInteger <> AlmacenID then
    begin
      MovID:=Folio('MovimientoAlmacen', '');
      AlmacenID:=dsInventario.FieldByName('IDAlmacen').AsInteger;
      dsTotalAlmacen.ParamByName('LiquidacionID').AsInteger:=LiquidacionID;
      dsTotalAlmacen.ParamByName('AlmacenID').AsInteger:=AlmacenID;
      dsTotalAlmacen.Open;
      cmdMov.ParamByName('MovimientoAlmacenID').AsInteger:=MovID;
      cmdMov.ParamByName('Folio').AsInteger:=MovID;
      cmdMov.ParamByName('Fecha').AsDateTime:=Trunc(Now);
      cmdMov.ParamByName('Ejercicio').AsString:=FormatDateTime('yyyy', Now);
      cmdMov.ParamByName('Periodo').AsString:=FormatDateTime('m', Now);
      cmdMov.ParamByName('Dia').AsString:=FormatDateTime('d', Now);
      cmdMov.ParamByName('Total').AsFloat:=Decimales(dsTotalAlmacen.FieldByName('Importe').AsFloat, 2);
      cmdMov.ParamByName('ImpuestoPorcentaje').AsFloat:=Decimales(dsTotalAlmacen.FieldByName('ImpuestoPorcentaje').AsFloat, 2);
      cmdMov.ParamByName('SubTotal').AsFloat:=Decimales(dsTotalAlmacen.FieldByName('SubTotal').AsFloat, 2);
      cmdMov.ParamByName('Impuesto').AsFloat:=Decimales(dsTotalAlmacen.FieldByName('Impuesto').AsFloat, 2);
      cmdMov.ParamByName('EstacionID').AsInteger:=dsTotalAlmacen.FieldByName('NUMEROESTACION').AsInteger;
      //cmdMov.ParamByName('BonoMerma').AsInteger:=0;
      cmdMov.ParamByName('EstacionDestinoID').AsInteger:=0;
      cmdMov.ParamByName('AlmacenDestinoID').AsInteger:=0;
      cmdMov.ParamByName('ProveedorID').AsInteger:=0;
      cmdMov.ParamByName('AlmacenID').AsInteger:=AlmacenID;
      cmdMov.ParamByName('TipoMovimientoAlmacenID').AsInteger:=2;
      cmdMov.Execute;
      dsTotalAlmacen.Close;
    end;
    cmdDet.ParamByName('DetalleMovimientoAlmacenID').AsInteger:=Folio('DetalleTransaccionID', '');
    cmdDet.ParamByName('MovimientoAlmacenID').AsInteger:=MovID;
    cmdDet.ParamByName('Cantidad').AsFloat:=Decimales(dsInventario.FieldByName('Cantidad').AsFloat, 2);
    cmdDet.ParamByName('Precio').AsFloat:=Decimales(dsInventario.FieldByName('Precio').AsFloat, 2);
    cmdDet.ParamByName('Importe').AsFloat:=Decimales(dsInventario.FieldByName('Importe').AsFloat, 2);
    cmdDet.ParamByName('ProductoID').AsInteger:=dsInventario.FieldByName('IDProducto').AsInteger;
    cmdDet.Execute;
    dsInventario.Next;
  end;
  dsInventario.Close;


  dsFaltantes:=Schema.NewDataset(Connection, 'spDiferenciasLiquidacion');
  dsFaltantes.ParamByName('LiquidacionID').AsInteger:=LiquidacionID;
  dsFaltantes.Open;
  cmdFyP:=Schema.NewCommand(Connection, 'Insert_dbo FaltanteyPago');
  cmdDetLiq:=Schema.NewCommand(Connection, 'Insert_dbo DetalleLiquidacion2');

  while not dsFaltantes.Eof do
  begin
    cmdFyP.ParamByName('FaltanteyPagoID').AsInteger:=Folio('FaltanteyPago', '');
    cmdFyP.ParamByName('Fecha').AsDateTime:=MiFecha;
    cmdFyP.ParamByName('Cargo').AsInteger:=0;
    cmdFyP.ParamByName('Abono').AsInteger:=0;
    cmdFyP.ParamByName('LiquidacionID').AsInteger:=LiquidacionID;
    cmdFyP.ParamByName('Descripcion').AsString:=Format('DIFERENCIA EN LIQUIDACION [%d-%d]', [MiEstacionID, dsFaltantes.FieldByName('IDTurno').AsInteger]);
    cmdFyP.ParamByName('EmpleadoID').AsInteger:=dsFaltantes.FieldByName('IDEMPLEADO').AsInteger;
    cmdDetLiq.ParamByName('DETALLELIQUIDACIONID').AsInteger:=Folio('IDDETALLEINGRESOS', '');
    cmdDetLiq.ParamByName('DESPACHADORLIQUIDACIONID').AsInteger:=dsFaltantes.FieldByName('IDENCARGADOINGRESOS').AsInteger;
    cmdDetLiq.ParamByName('Cantidad').AsInteger:=1;
    cmdDetLiq.ParamByName('Ticket').AsInteger:=0;
    cmdDetLiq.ParamByName('CuponID').AsInteger:=0;
    cmdDetLiq.ParamByName('SalidaID').AsInteger:=0;
    cmdDetLiq.ParamByName('ClienteID').AsInteger:=0;
    cmdDetLiq.ParamByName('BancoID').AsInteger:=0;
    cmdDetLiq.ParamByName('ProductoID').AsInteger:=0;
    cmdDetLiq.ParamByName('AuxiliarID').AsInteger:=0;
    //cmdDetLiq.ParamByName('Facturado').AsBoolean:=False;
    cmdDetLiq.ParamByName('Importe').AsFloat:=Abs(Decimales(dsFaltantes.FieldByName('Diferencia').AsFloat, 2));

    if dsFaltantes.FieldByName('Diferencia').AsFloat < 0 then
    begin
      cmdDetLiq.ParamByName('TipoValorID').AsInteger:=15;
      cmdDetLiq.ParamByName('Referencia').AsString:=Format('FALTANTE EN LIQUIDACION [%d]', [dsFaltantes.FieldByName('IDTurno').AsInteger]);
      cmdFyP.ParamByName('Cargo').AsFloat:=Abs(Decimales(dsFaltantes.FieldByName('Diferencia').AsFloat, 2));
      cmdFyP.ParamByName('TipoFaltantePagoID').AsInteger:=1;
      cmdFyP.Execute;
    end
    else
    begin
      cmdDetLiq.ParamByName('TipoValorID').AsInteger:=16;
      cmdDetLiq.ParamByName('Referencia').AsString:=Format('SOBRANTE EN LIQUIDACION [%d]', [dsFaltantes.FieldByName('IDTurno').AsInteger]);
      cmdFyP.ParamByName('Abono').AsFloat:=Abs(Decimales(dsFaltantes.FieldByName('Diferencia').AsFloat, 2));
      cmdFyP.ParamByName('TipoFaltantePagoID').AsInteger:=2;
      if ServerDataModule.AplicaSobrantes then
        cmdFyP.Execute;
    end;
    cmdDetLiq.Execute;
    dsFaltantes.Next;
  end;
  dsFaltantes.Close;
  cmdCierra:=Schema.NewCommand(Connection, 'CierraLiquidacion');
  cmdCierra.ParamByName('LiquidacionID').AsInteger:=LiquidacionID;
  cmdCierra.Execute;
end;

function TServiceIngresos.CostoProducto(const IDPRODUCTO: Integer): Double;
var
  ds: IDADataSet;
begin
  ds:=Schema.NewDataset(Connection, 'spCostoProducto');
  ds.ParamByName('ProductoID').AsInteger:=IDPRODUCTO;
  ds.Open;
  Result:=ds.FieldByName('Costo').AsFloat;
  ds.Close;
end;

function TServiceIngresos.TipoCalificacion: Integer;
begin
end;

function TServiceIngresos.DatosAlumno(const AlumnoID: Integer): TDatos;
begin
end;

function TServiceIngresos.DatosMaestro(const MaestroID: Integer): TDatos;
begin
end;

function TServiceIngresos.PagoBanco(const FECHAPAGO: DateTime; const IDEMPLEADO: Integer; const IDPAGO: Integer; const MONTO: Double): Integer;
begin
end;

function TServiceIngresos.PrecioProducto(const ProductoID: Integer): Double;
var
  ds: IDADataSet;
begin
  try
    ds := Schema.NewDataset(Connection, 'spPrecioProducto');
    ds.ParamByName('ProductoID').AsInteger := ProductoID;
    ds.Open;
    Result := ds.FieldByName('PrecioVenta').AsFloat;
  finally
    ds.Close;
  end;
end;

function TServiceIngresos.FolioActual(const Campo: AnsiString; const Serie: AnsiString): Integer;
var
  ds: IDADataSet;
begin
  ds:=Schema.NewDataset(Connection, 'spFolioActual');
  ds.ParamByName('Campo').AsString:=Campo;
  ds.ParamByName('Serie').AsString:=Serie;
  ds.Open;
  Result:=ds.FieldByName('Folio').AsInteger;
  ds.Close;
end;

function TServiceIngresos.ValidaFolioFactura(const Campo: AnsiString; const Folio: Integer): Boolean;
var
  ds: IDADataset;
begin
  ds:=Schema.NewDataset(Connection, 'spValidaFolioFactura');
  ds.ParamByName('Serie').AsString:=Campo;
  ds.ParamByName('Folio').AsInteger:=Folio;
  ds.Open;
  Result:=ds.IsEmpty;
  ds.Close;
end;

function TServiceIngresos.GuardarDatosFactura(const DatosFactura: TDatosFactura): AnsiString;
var
  cmdFactura:IDASQLCommand;
  cmdDetalles:IDASQLCommand;
  dsConfiguracion: IDADataSet;
  cmdActualizaFacturaE:IDASQLCommand;

  I:integer;
  J:integer;
  Datos: TDatosFactura;

  ProveedorTimbrado : TProveedorAutorizadoCertificacion;
  TimbreDeFactura : TFETimbre;
  archivoFacturaXML, rutaImagenCBB: String;
  Factura: TFacturaElectronica;
  Emisor, Receptor: TFEContribuyente;
  Certificado: TFECertificado;
  ImpuestoRetenido, Impuesto1: TFEImpuestoRetenido;
  ImpuestoTraslado, Impuesto2 : TFEImpuestoTrasladado;
  ImpuestoLocal: TFEImpuestoLocal;
  Concepto, Concepto1, Concepto2 : TFEConcepto;
  generadorCBB: TGeneradorCBB;
  CredencialesPAC: TFEPACCredenciales;
  ReferenciaTimbre: String;

  FolioFE: Integer;
const
  _URL_ECODEX_PRUEBAS = 'https://pruebas.ecodex.com.mx:2045';

begin
  Datos:=TDatosFactura.Create;
  try
    Datos.Assign(DatosFactura);
    CalculaIEPS(Datos);

    cmdFactura:=Schema.NewCommand(Connection,'spInsertarFactura') ;
    cmdFactura.ParamByName('FacturaID').AsInteger:=Datos.Factura.FacturaID;
    FolioFE:= Folio('FolioFactura',Datos.Factura.Serie);
    cmdFactura.ParamByName('Folio').AsInteger:=FolioFE;
    cmdFactura.ParamByName('Serie').AsString:=Datos.Factura.Serie;
    cmdFactura.ParamByName('Fecha').AsDateTime:=Datos.Factura.Fecha;
    cmdFactura.ParamByName('Ejercicio').AsString:=FormatDateTime('yyyy', Datos.Factura.Fecha);
    cmdFactura.ParamByName('Periodo').AsString:=FormatDateTime('m', Datos.Factura.Fecha);
    cmdFactura.ParamByName('Dia').AsString:=FormatDateTime('d', Datos.Factura.Fecha);
    cmdFactura.ParamByName('SubTotal').AsFloat:=Datos.Factura.Subtotal;
    cmdFactura.ParamByName('Impuesto').AsFloat:=Datos.Factura.Impuesto;
    cmdFactura.ParamByName('Total').AsFloat:=Datos.Factura.Total;
    cmdFactura.ParamByName('ImpuestoPorcentaje').AsFloat:=Datos.Factura.ImpuestoPorcentaje;
    cmdFactura.ParamByName('ClienteID').AsInteger:=Datos.Factura.ClienteID;
    cmdFactura.ParamByName('FormaPagoID').AsInteger:=Datos.Factura.FormaPagoID;
    cmdFactura.ParamByName('UsuarioID').AsInteger:=Datos.Factura.UsuarioID;
    cmdFactura.ParamByName('NumeroEstacion').AsInteger:= Datos.Factura.NumeroEstacion;
    cmdFactura.ParamByName('Tickets').AsString:= Datos.Factura.Tickets;
    cmdFactura.ParamByName('TipoFacturaID').AsInteger:= Datos.Factura.IDCondicionPago;
    cmdFactura.Execute;

    cmdDetalles:=Schema.NewCommand(Connection,'spInsertarDetalleFactura') ;
    for I := 0 to Datos.Detalles.Count - 1 do
    begin
      cmdDetalles.ParamByName('DetalleFacturaID').AsInteger:=Folio('DetalleFactura','');
      cmdDetalles.ParamByName('Cantidad').AsFloat:=Datos.Detalles.Items[I].Cantidad;
      cmdDetalles.ParamByName('Precio').AsFloat:=Datos.Detalles.Items[I].Precio;
      cmdDetalles.ParamByName('Importe').AsFloat:=Datos.Detalles.Items[I].Importe;
      cmdDetalles.ParamByName('ItemNo').AsInteger:=I;
      cmdDetalles.ParamByName('FacturaID').AsInteger:=Datos.Factura.FacturaID;
      cmdDetalles.ParamByName('ProductoID').AsInteger:=Datos.Detalles.Items[I].ProductoID;
      cmdDetalles.Execute;
    end;


  finally
    ///////////FACTURA ELECTRONICA//////////////////////////////////////////////
    Try
      // 1. Definimos los datos del emisor y receptor

      // Si se desea probar al PAC FinkOk usar el siguiente Emisor:
      //Emisor.RFC:='AAD990814BP7';
      // Si se desea usar al PAC Ecodex usar al siguiente Emisor
      Emisor.RFC                     :=Datos.Emisor.RFC;
      Emisor.Nombre                  :=Datos.Emisor.NOMBRE;
      Emisor.Direccion.Calle         :=Datos.Emisor.CALLE;
      Emisor.Direccion.NoExterior    :=Datos.Emisor.NOINTERIOR;
      Emisor.Direccion.NoInterior    :=Datos.Emisor.NOEXTERIOR;
      Emisor.Direccion.CodigoPostal  :=Datos.Emisor.CODIGOPOSTAL;
      Emisor.Direccion.Colonia       :=Datos.Emisor.COLONIA;
      Emisor.Direccion.Municipio     :=Datos.Emisor.MUNICIPIO;
      Emisor.Direccion.Estado        :=Datos.Emisor.ESTADO;
      Emisor.Direccion.Pais          :=Datos.Emisor.PAIS;
      Emisor.Direccion.Localidad     :=Datos.Emisor.LOCALIDAD;

       // 2. Agregamos los régimenes fiscales (requerido en CFD >= 2.2)
      SetLength(Emisor.Regimenes, 1);
      Emisor.Regimenes[0]            := Datos.Emisor.REGIMENFISCAL;

      // Asignamos los valores iguales a la direcion del emisor suponiendo que se genera en el mismo lugar que se emitio
      Emisor.ExpedidoEn.Calle        :=Datos.EmisorExpedidoEn.CALLE;
      Emisor.ExpedidoEn.NoExterior   :=Datos.EmisorExpedidoEn.NOEXTERIOR;
      Emisor.ExpedidoEn.NoInterior   :=Datos.EmisorExpedidoEn.NOINTERIOR;
      Emisor.ExpedidoEn.CodigoPostal :=Datos.EmisorExpedidoEn.CODIGOPOSTAL;
      Emisor.ExpedidoEn.Colonia      :=Datos.EmisorExpedidoEn.COLONIA;
      Emisor.ExpedidoEn.Municipio    :=Datos.EmisorExpedidoEn.MUNICIPIO;
      Emisor.ExpedidoEn.Estado       :=Datos.EmisorExpedidoEn.ESTADO;
      Emisor.ExpedidoEn.Pais         :=Datos.EmisorExpedidoEn.PAIS;
      Emisor.ExpedidoEn.Localidad    :=Datos.EmisorExpedidoEn.LOCALIDAD;
      Emisor.ExpedidoEn.Referencia   :=Datos.EmisorExpedidoEn.REFERENCIA;

      Receptor.RFC                   :=Datos.Receptor.RFC;
      Receptor.Nombre                :=Datos.Receptor.NOMBRE;
      Receptor.Direccion.Calle       :=Datos.Receptor.CALLE;
      Receptor.Direccion.NoExterior  :=Datos.Receptor.NOEXTERIOR;
      Receptor.Direccion.NoInterior  :=Datos.Receptor.NOINTERIOR;
      Receptor.Direccion.CodigoPostal:=Datos.Receptor.CODIGOPOSTAL;
      Receptor.Direccion.Colonia     :=Datos.Receptor.COLONIA;
      Receptor.Direccion.Municipio   :=Datos.Receptor.MUNICIPIO;
      Receptor.Direccion.Estado      :=Datos.Receptor.ESTADO;
      Receptor.Direccion.Pais        :=Datos.Receptor.PAIS;
      Receptor.Direccion.Localidad   :=Datos.Receptor.LOCALIDAD;

      // 4. Definimos el certificado junto con su llave privada
      Certificado.Ruta:=ExtractFilePath(Application.ExeName) + '\' + inttostr(Datos.Factura.NumeroEstacion)+ '\' + Emisor.RFC + '.cer';
      Certificado.LlavePrivada.Ruta:=ExtractFilePath(Application.ExeName) + '\' + inttostr(Datos.Factura.NumeroEstacion)+ '\' + Emisor.RFC + '.key';
      Certificado.LlavePrivada.Clave:='12345678a';
      //Certificado.Ruta              := Datos.Emisor.ARCHIVOCERTIFICADO;
      //Certificado.LlavePrivada.Ruta := Datos.Emisor.ARCHIVOLLAVEPRIVADA;
      //Certificado.LlavePrivada.Clave:= Datos.Emisor.CLAVELLAVEPRIVADA;

      // 5. Creamos la clase Factura con los parametros minimos.
      //WriteLn('Generando factura CFDI ...');
      Factura:=TFacturaElectronica.Create(Emisor, Receptor, Certificado, tcIngreso);

      //Factura.AutoAsignarFechaGeneracion := False;
      //Factura.FechaGeneracion := EncodeDateTime(2012, 05, 12, 19, 47, 22, 0);
      //Factura.OnComprobanteGenerado:=onComprobanteGenerado;

      // Asignamos el método de pago, de momento funciona con la cadena "Efectivo"
      // o el numero de catálogo.
      //Factura.MetodoDePago:='Efectivo';
      Factura.MetodoDePago := Datos.Emisor.METODOPAGO;
      Factura.NumeroDeCuenta:=Datos.EmisorExpedidoen.NUMERODECUENTA;

      // Asignamos el lugar de expedición (requerido en  CFD >= 2.2)
      Factura.LugarDeExpedicion:= Datos.EmisorExpedidoen.LUGARDEEXPEDICION;

      for I := 0 to Datos.Detalles.Count - 1 do
      begin
        Concepto.Cantidad     := Datos.Detalles.Items[I].Cantidad;
        Concepto.Unidad       := Datos.Detalles.Items[I].Unidad;
        Concepto.Descripcion  := Datos.Detalles.Items[I].Descripcion;
        Concepto.ValorUnitario:= Datos.Detalles.Items[I].Precio;
        Factura.AgregarConcepto(Concepto);
      end;

      ImpuestoTraslado.Nombre:='IVA';
      ImpuestoTraslado.Tasa:= Datos.Factura.ImpuestoPorcentaje;
      ImpuestoTraslado.Importe:= Datos.Factura.Impuesto;
      Factura.AgregarImpuestoTrasladado(ImpuestoTraslado);

      // Le damos un descuento
      //Factura.AsignarDescuento(5, 'Por pronto pago');

      // Mandamos generar la factura con el siguiente folio disponible
      if Not(DirectoryExists(GetDesktopFolder() + '\Prueba-CFDI')) then
        CreateDir(GetDesktopFolder() + '\Prueba-CFDI');

      archivoFacturaXML:=GetDesktopFolder() + '\Prueba-CFDI\MiFactura.xml';
      //rutaImagenCBB := GetDesktopFolder() + '\Prueba-CFDI\MiFactura-CBB.jpg';

      // Mandamos generar el CFD en memoria antes de timbrarlo
      //Factura.Generar(12345, fpUnaSolaExhibicion);
      Factura.Generar(FolioFE, Datos.Factura.Serie, fpUnaSolaExhibicion);

      // Ya que tenemos el comprobante, lo mandamos timbrar con el PAC de nuestra elección,
      // por cuestiones de ejemplo, usaremos al PAC "Ecodex"

      //ProveedorTimbrado := TPACFinkOk.Create;
      if ECODEX = 'SI' then
         ProveedorTimbrado := TPACEcodex.Create(_URL_ECODEX_PRUEBAS);
      if COMERCIODIGITAL = 'SI' then
         ProveedorTimbrado := TPACComercioDigital.Create; // Si queremos usar a Comercio Digital solo des-comentamos aqui

      try
        CredencialesPAC.RFC   := CREDENCIALESPACKRFC;
        CredencialesPAC.Clave := CREDENCIALESPACKCLAVE;
        CredencialesPac.Certificado:= Certificado;  // Si queremos usar a Comercio Digital solo des-comentamos aqui

        // Este es el "ID de Integrador" de pruebas de Ecodex
        if ECODEX = 'SI' then
           CredencialesPAC.DistribuidorID := CREDENCIALESPACK_ECODEX_DISTRIBUIDORID;

        // Asignamos nuestras credenciales de acceso con el PAC (en caso de Ecodex asignamos la credencial como usuario e integrador)
        if ECODEX = 'SI' then
           ProveedorTimbrado.AsignarCredenciales(CredencialesPAC, CredencialesPAC);
        if COMERCIODIGITAL = 'SI' then
           ProveedorTimbrado.AsignarCredenciales(CredencialesPAC);  // Si queremos usar a Comercio Digital solo des-comentamos aqui

        // Mandamos timbrar el documento al PAC
        TimbreDeFactura := ProveedorTimbrado.TimbrarDocumento(Factura.XML);

        // Asignamos el timbre a la factura para que sea válida
        try
          Factura.AsignarTimbreFiscal(TimbreDeFactura);
          ReferenciaTimbre:= TimbreDeFactura.Referencia
        except ReferenciaTimbre:= TimbreDeFactura.Referencia end;

        //ACTUALIZAR DATOS DE FACTURA ELECTRONICA CFDI
        cmdActualizaFacturaE:=Schema.NewCommand(Connection,'spActualizaDatosFE') ;
        cmdActualizaFacturaE.ParamByName('CADENAORIGINAL').AsString:= Factura.CadenaOriginal;
        cmdActualizaFacturaE.ParamByName('SELLODIGITAL').AsString:= Factura.SelloDigital;
        cmdActualizaFacturaE.ParamByName('XML').AsString:= Factura.XML;
        cmdActualizaFacturaE.ParamByName('NoCertificado').AsString:= Factura.Certificado.NumeroSerie;
        cmdActualizaFacturaE.ParamByName('FechaFacturaE').AsDateTime:= Factura.FechaGeneracion;
        //cmdActualizaFacturaE.ParamByName('NoAprobacion').AsString:= Factura.
        //cmdActualizaFacturaE.ParamByName('EjercicioAprobacion').AsString:= Factura.
        cmdActualizaFacturaE.ParamByName('VersionSAT').AsString:= '32';
        cmdActualizaFacturaE.ParamByName('UUID').AsString:= Factura.Timbre.UUID;
        cmdActualizaFacturaE.ParamByName('FechaTimbrado').AsDateTime:= Factura.Timbre.FechaTimbrado;
        cmdActualizaFacturaE.ParamByName('NoCertificadoSAT').AsString:= Factura.Timbre.NoCertificadoSAT;
        cmdActualizaFacturaE.ParamByName('SELLOSAT').AsString:= Factura.Timbre.SelloSAT;
        cmdActualizaFacturaE.ParamByName('CADENATIMBRE').AsString:= '||1.0|'+Factura.Timbre.UUID+'|'+formatdatetime('yyyy-mm-dd',Factura.Timbre.FechaTimbrado)+'T'+formatdatetime('hh:mm:ss',Factura.Timbre.FechaTimbrado)+
                                                                    '|'+Factura.Timbre.SelloSAT+'|'+Factura.Timbre.NoCertificadoSAT+
                                                                    '||';
        cmdActualizaFacturaE.ParamByName('CBB').AsString:= Format('?re=%s&rr=%s&tt=%s&id=%s',
                                                                  [Emisor.RFC,
                                                                   Receptor.RFC,
                                                                   FloatToStrF(Factura.Total, ffFixed, 17, 6),
                                                                   Factura.Timbre.UUID]);

        cmdActualizaFacturaE.ParamByName('ACUSE').AsString:= ReferenciaTimbre;
        cmdActualizaFacturaE.ParamByName('FacturaID').AsInteger:= Datos.Factura.FacturaID;
        cmdActualizaFacturaE.ParamByName('EstacionID').AsInteger:= Datos.Factura.NumeroEstacion;
        cmdActualizaFacturaE.Execute;


        // Guardamos la factura una vez timbrada
        Factura.Guardar(archivoFacturaXML);
        // *********** PARA LA REPRESENTACION GRAFICA ***********
        // Generamos el CBB del CFDI
        //generadorCBB := TGeneradorCBB.Create;
        // Generamos el CBB que por default se genera de 1200x1200px para que tenga la resolucion necesaria
        //generadorCBB.GenerarImagen(Emisor,
        //                           Receptor,
        //                           Factura.Total,
        //                           TimbreDeFactura.UUID,
        //                           rutaImagenCBB);
        //generadorCBB.Free;

        // Generamos la Cadena Original del Timbre:
        //Writeln('Cadena Original del Timbre Fiscal:');
        //Writeln(Factura.CadenaOriginalTimbre);

        //WriteLn('CFDI generado con éxito en ' + archivoFacturaXML + '. Presiona cualquier tecla para cancelarlo');
        //Readln;

        // Para cancelar el CFDI simplemente hacemos la siguiente llamada
        //Writeln('Mandando cancelar la factura con el PAC...');
        //if ProveedorTimbrado.CancelarDocumento(Factura.XML) then
        //  Writeln('El CFDI fue cancelado correctamente. Presiona cualquier tecla para salir')
        //else
        //  Writeln('El CFDI no pudo ser cancelado.');

        //Readln;
      finally
        ProveedorTimbrado.Free;
        FreeAndNil(Factura);

        result:= 'OK';
      end;

    except
    on E: Exception do
    begin
      result:= E.Message;
      //WriteLn('Ocurrio un error:');
      //Writeln(E.ClassName, ': ', E.Message);
      //ReadLn;
    end;

    End;


    Datos.Free;
  end;
end;

procedure TServiceIngresos.CalculaIEPS(var Datos: TDatosFactura);
var
  Aux, Impuesto: Double;
  SubTotal: Double;
  I: Integer;
begin
  SubTotal:=0;
  for I := 0 to Datos.Detalles.Count - 1 do
  begin
    Impuesto:=IEPS(Datos.Detalles[I].ProductoID);
    Aux:=Datos.Detalles[I].Precio - Impuesto;
    Aux:=Aux / (1 + (Datos.Factura.ImpuestoPorcentaje / 100));
    Aux:=Aux + Impuesto;
    Aux:=Decimales(Aux, 6);
    Datos.Detalles[I].Precio:=Aux;
    Datos.Detalles[I].Cantidad:=Decimales(Datos.Detalles[I].Cantidad, 4);
    Datos.Detalles[I].Importe:=Decimales(Aux * Datos.Detalles[I].Cantidad, 2);
    SubTotal:=SubTotal + Datos.Detalles[I].Importe;
  end;
  Datos.Factura.Total:=Decimales(Datos.Factura.Total, 2);
  Datos.Factura.Subtotal:=Decimales(SubTotal, 2);
  Datos.Factura.Impuesto:=Decimales(Datos.Factura.Total - SubTotal, 2);
end;

var
  fClassFactory: IROClassFactory;
initialization
  fClassFactory := TROClassFactory.Create('ServiceIngresos', Create_ServiceIngresos, TServiceIngresos_Invoker);

finalization
  UnRegisterClassFactory(fClassFactory);
  fClassFactory := nil;

end.
