unit LibraryGauss_Invk;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I Remobjects.inc}

interface

uses
  {vcl:} Classes,
  {RemObjects:} uROXMLIntf, uROServer, uROServerIntf, uROTypes, uROClientIntf,
  {Used RODL Intf's:} DataAbstract4_Intf,
  {Used RODL Invk's:} DataAbstract4_Invk,
  {Generated:} LibraryGauss_Intf;

type
  TServiceGauss_Invoker = class(TDataAbstractService_Invoker)
  private
  protected
  public
    constructor Create; override;
  published
    procedure Invoke_AbreDataSetReportes(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_BuscarReporte(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DragPagoMateria(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ActualizaSubTipoPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DatosFacturaElectronica(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_Fecha(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_Folio(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_GuardaDatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_Login(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_IniciaCiclo(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ModificarFolioActual(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_InsertaFacturaElectronica(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_FolioActual2(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_GuardaAccesos(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_EliminaMaestroDisponibilidad(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_EliminaMateriaMaestro(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_EliminaPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_EliminaPagoCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_InsertaCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_LiquidaPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DividePago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_InsertaPagoCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_AplicaCalificacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_HistorialAlumnoDEL(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_BecaDescuento(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_InsertaHistorialAlumno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_CambioGrupo(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_TipoCalificacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DatosAlumno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DatosMaestro(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_PagoBanco(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_PrecioProducto(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_FolioActual(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ValidaFolioFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_GuardarDatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_CadenaOriginal(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
  end;

implementation

uses
  {RemObjects:} uRORes, uROClient;

{ TServiceGauss_Invoker }

constructor TServiceGauss_Invoker.Create;
begin
  inherited Create;
  FAbstract := False;
end;

procedure TServiceGauss_Invoker.Invoke_AbreDataSetReportes(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function AbreDataSetReportes(const SQL: AnsiString; const Parametros: TParametrosF): Binary; }
var
  SQL: AnsiString;
  Parametros: LibraryGauss_Intf.TParametrosF;
  lResult: Binary;
  __lObjectDisposer: TROObjectDisposer;
begin
  Parametros := nil;
  lResult := nil;
  try
    __Message.Read('SQL', TypeInfo(AnsiString), SQL, []);
    __Message.Read('Parametros', TypeInfo(LibraryGauss_Intf.TParametrosF), Parametros, []);

    lResult := (__Instance as IServiceGauss).AbreDataSetReportes(SQL, Parametros);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'AbreDataSetReportesResponse');
    __Message.Write('Result', TypeInfo(Binary), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(Parametros);
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceGauss_Invoker.Invoke_BuscarReporte(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function BuscarReporte(const Nombre: AnsiString): TReporteF; }
var
  Nombre: AnsiString;
  lResult: LibraryGauss_Intf.TReporteF;
  __lObjectDisposer: TROObjectDisposer;
begin
  lResult := nil;
  try
    __Message.Read('Nombre', TypeInfo(AnsiString), Nombre, []);

    lResult := (__Instance as IServiceGauss).BuscarReporte(Nombre);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'BuscarReporteResponse');
    __Message.Write('Result', TypeInfo(LibraryGauss_Intf.TReporteF), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceGauss_Invoker.Invoke_DragPagoMateria(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DragPagoMateria(const PAGOMATERIA: Integer; const IDGRUPOTARGET: Integer; const IDGRUPOSOURCE: Integer): Boolean; }
var
  PAGOMATERIA: Integer;
  IDGRUPOTARGET: Integer;
  IDGRUPOSOURCE: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('PAGOMATERIA', TypeInfo(Integer), PAGOMATERIA, []);
    __Message.Read('IDGRUPOTARGET', TypeInfo(Integer), IDGRUPOTARGET, []);
    __Message.Read('IDGRUPOSOURCE', TypeInfo(Integer), IDGRUPOSOURCE, []);

    lResult := (__Instance as IServiceGauss).DragPagoMateria(PAGOMATERIA, IDGRUPOTARGET, IDGRUPOSOURCE);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'DragPagoMateriaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_ActualizaSubTipoPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ActualizaSubTipoPago(const IDTIPOPAGO: Integer; const IDSUBTIPOPAGO: Integer): Boolean; }
var
  IDTIPOPAGO: Integer;
  IDSUBTIPOPAGO: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('IDTIPOPAGO', TypeInfo(Integer), IDTIPOPAGO, []);
    __Message.Read('IDSUBTIPOPAGO', TypeInfo(Integer), IDSUBTIPOPAGO, []);

    lResult := (__Instance as IServiceGauss).ActualizaSubTipoPago(IDTIPOPAGO, IDSUBTIPOPAGO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'ActualizaSubTipoPagoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_DatosFacturaElectronica(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DatosFacturaElectronica(const FacturaID: Integer): TFacturaElectronicaF; }
var
  FacturaID: Integer;
  lResult: LibraryGauss_Intf.TFacturaElectronicaF;
  __lObjectDisposer: TROObjectDisposer;
begin
  lResult := nil;
  try
    __Message.Read('FacturaID', TypeInfo(Integer), FacturaID, []);

    lResult := (__Instance as IServiceGauss).DatosFacturaElectronica(FacturaID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'DatosFacturaElectronicaResponse');
    __Message.Write('Result', TypeInfo(LibraryGauss_Intf.TFacturaElectronicaF), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceGauss_Invoker.Invoke_DatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DatosFactura(const Folio: Integer; const Serie: AnsiString): Boolean; }
var
  Folio: Integer;
  Serie: AnsiString;
  lResult: Boolean;
begin
  try
    __Message.Read('Folio', TypeInfo(Integer), Folio, []);
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);

    lResult := (__Instance as IServiceGauss).DatosFactura(Folio, Serie);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'DatosFacturaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_Fecha(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function Fecha: DateTime; }
var
  lResult: DateTime;
begin
  try
    lResult := (__Instance as IServiceGauss).Fecha;

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'FechaResponse');
    __Message.Write('Result', TypeInfo(DateTime), lResult, [paIsDateTime]);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_Folio(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function Folio(const Campo: AnsiString; const Serie: AnsiString): Integer; }
var
  Campo: AnsiString;
  Serie: AnsiString;
  lResult: Integer;
begin
  try
    __Message.Read('Campo', TypeInfo(AnsiString), Campo, []);
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);

    lResult := (__Instance as IServiceGauss).Folio(Campo, Serie);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'FolioResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_GuardaDatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ procedure GuardaDatosFactura(const DatosFactura: TDatosFactura); }
var
  DatosFactura: LibraryGauss_Intf.TDatosFactura;
  __lObjectDisposer: TROObjectDisposer;
begin
  DatosFactura := nil;
  try
    __Message.Read('DatosFactura', TypeInfo(LibraryGauss_Intf.TDatosFactura), DatosFactura, []);

    (__Instance as IServiceGauss).GuardaDatosFactura(DatosFactura);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'GuardaDatosFacturaResponse');
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

    __oResponseOptions := [roNoResponse];

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(DatosFactura);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceGauss_Invoker.Invoke_Login(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function Login(const Usuario: AnsiString; const Clave: AnsiString): TLoginInfoF; }
var
  Usuario: AnsiString;
  Clave: AnsiString;
  lResult: LibraryGauss_Intf.TLoginInfoF;
  __lObjectDisposer: TROObjectDisposer;
begin
  lResult := nil;
  try
    __Message.Read('Usuario', TypeInfo(AnsiString), Usuario, []);
    __Message.Read('Clave', TypeInfo(AnsiString), Clave, []);

    lResult := (__Instance as IServiceGauss).Login(Usuario, Clave);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'LoginResponse');
    __Message.Write('Result', TypeInfo(LibraryGauss_Intf.TLoginInfoF), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceGauss_Invoker.Invoke_IniciaCiclo(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function IniciaCiclo(const IDCICLO: AnsiString): Boolean; }
var
  IDCICLO: AnsiString;
  lResult: Boolean;
begin
  try
    __Message.Read('IDCICLO', TypeInfo(AnsiString), IDCICLO, []);

    lResult := (__Instance as IServiceGauss).IniciaCiclo(IDCICLO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'IniciaCicloResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_ModificarFolioActual(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ModificarFolioActual(const Campo: AnsiString; const Serie: AnsiString; const FolioNew: Integer): AnsiString; }
var
  Campo: AnsiString;
  Serie: AnsiString;
  FolioNew: Integer;
  lResult: AnsiString;
begin
  try
    __Message.Read('Campo', TypeInfo(AnsiString), Campo, []);
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);
    __Message.Read('FolioNew', TypeInfo(Integer), FolioNew, []);

    lResult := (__Instance as IServiceGauss).ModificarFolioActual(Campo, Serie, FolioNew);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'ModificarFolioActualResponse');
    __Message.Write('Result', TypeInfo(AnsiString), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_InsertaFacturaElectronica(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ procedure InsertaFacturaElectronica(const FacturaElectronicaID: Integer; const CadenaOriginal: Widestring; const SelloDigital: Widestring; 
                                        const FacturaID: Integer; const Vigencia: Boolean; const Enviado: Boolean; const NoCertificado: AnsiString; 
                                        const NoAprobacion: AnsiString; const FechaAprobacion: DateTime); }
var
  FacturaElectronicaID: Integer;
  CadenaOriginal: Widestring;
  SelloDigital: Widestring;
  FacturaID: Integer;
  Vigencia: Boolean;
  Enviado: Boolean;
  NoCertificado: AnsiString;
  NoAprobacion: AnsiString;
  FechaAprobacion: DateTime;
begin
  try
    __Message.Read('FacturaElectronicaID', TypeInfo(Integer), FacturaElectronicaID, []);
    __Message.Read('CadenaOriginal', TypeInfo(Widestring), CadenaOriginal, []);
    __Message.Read('SelloDigital', TypeInfo(Widestring), SelloDigital, []);
    __Message.Read('FacturaID', TypeInfo(Integer), FacturaID, []);
    __Message.Read('Vigencia', TypeInfo(Boolean), Vigencia, []);
    __Message.Read('Enviado', TypeInfo(Boolean), Enviado, []);
    __Message.Read('NoCertificado', TypeInfo(AnsiString), NoCertificado, []);
    __Message.Read('NoAprobacion', TypeInfo(AnsiString), NoAprobacion, []);
    __Message.Read('FechaAprobacion', TypeInfo(DateTime), FechaAprobacion, [paIsDateTime]);

    (__Instance as IServiceGauss).InsertaFacturaElectronica(FacturaElectronicaID, CadenaOriginal, SelloDigital, FacturaID, Vigencia, Enviado, NoCertificado, NoAprobacion, FechaAprobacion);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'InsertaFacturaElectronicaResponse');
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

    __oResponseOptions := [roNoResponse];

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_FolioActual2(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function FolioActual2(const Serie: AnsiString; const folio: Integer): Integer; }
var
  Serie: AnsiString;
  folio: Integer;
  lResult: Integer;
begin
  try
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);
    __Message.Read('folio', TypeInfo(Integer), folio, []);

    lResult := (__Instance as IServiceGauss).FolioActual2(Serie, folio);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'FolioActual2Response');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_GuardaAccesos(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ procedure GuardaAccesos(const UsuarioID: Integer; const Lista: AnsiString); }
var
  UsuarioID: Integer;
  Lista: AnsiString;
begin
  try
    __Message.Read('UsuarioID', TypeInfo(Integer), UsuarioID, []);
    __Message.Read('Lista', TypeInfo(AnsiString), Lista, []);

    (__Instance as IServiceGauss).GuardaAccesos(UsuarioID, Lista);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'GuardaAccesosResponse');
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

    __oResponseOptions := [roNoResponse];

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_EliminaMaestroDisponibilidad(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function EliminaMaestroDisponibilidad(const IDMAESTRODISPONIBILIDAD: Integer): Boolean; }
var
  IDMAESTRODISPONIBILIDAD: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('IDMAESTRODISPONIBILIDAD', TypeInfo(Integer), IDMAESTRODISPONIBILIDAD, []);

    lResult := (__Instance as IServiceGauss).EliminaMaestroDisponibilidad(IDMAESTRODISPONIBILIDAD);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'EliminaMaestroDisponibilidadResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_EliminaMateriaMaestro(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function EliminaMateriaMaestro(const IDMAESTRO: Integer; const IDMATERIA: Integer): Boolean; }
var
  IDMAESTRO: Integer;
  IDMATERIA: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('IDMAESTRO', TypeInfo(Integer), IDMAESTRO, []);
    __Message.Read('IDMATERIA', TypeInfo(Integer), IDMATERIA, []);

    lResult := (__Instance as IServiceGauss).EliminaMateriaMaestro(IDMAESTRO, IDMATERIA);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'EliminaMateriaMaestroResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_EliminaPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function EliminaPago(const idSubtipoPago: Integer; const status: AnsiString; const idCiclos: Integer; const idGrupo: Integer): Boolean; }
var
  idSubtipoPago: Integer;
  status: AnsiString;
  idCiclos: Integer;
  idGrupo: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('idSubtipoPago', TypeInfo(Integer), idSubtipoPago, []);
    __Message.Read('status', TypeInfo(AnsiString), status, []);
    __Message.Read('idCiclos', TypeInfo(Integer), idCiclos, []);
    __Message.Read('idGrupo', TypeInfo(Integer), idGrupo, []);

    lResult := (__Instance as IServiceGauss).EliminaPago(idSubtipoPago, status, idCiclos, idGrupo);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'EliminaPagoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_EliminaPagoCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function EliminaPagoCaja(const idSubtipoPago: Integer; const status: AnsiString; const idCiclos: Integer; const idGrupo: Integer): Boolean; }
var
  idSubtipoPago: Integer;
  status: AnsiString;
  idCiclos: Integer;
  idGrupo: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('idSubtipoPago', TypeInfo(Integer), idSubtipoPago, []);
    __Message.Read('status', TypeInfo(AnsiString), status, []);
    __Message.Read('idCiclos', TypeInfo(Integer), idCiclos, []);
    __Message.Read('idGrupo', TypeInfo(Integer), idGrupo, []);

    lResult := (__Instance as IServiceGauss).EliminaPagoCaja(idSubtipoPago, status, idCiclos, idGrupo);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'EliminaPagoCajaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_InsertaCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function InsertaCaja(const Observaciones: AnsiString; const TipoPago: AnsiString; const idEmpleado: Integer): Integer; }
var
  Observaciones: AnsiString;
  TipoPago: AnsiString;
  idEmpleado: Integer;
  lResult: Integer;
begin
  try
    __Message.Read('Observaciones', TypeInfo(AnsiString), Observaciones, []);
    __Message.Read('TipoPago', TypeInfo(AnsiString), TipoPago, []);
    __Message.Read('idEmpleado', TypeInfo(Integer), idEmpleado, []);

    lResult := (__Instance as IServiceGauss).InsertaCaja(Observaciones, TipoPago, idEmpleado);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'InsertaCajaResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_LiquidaPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function LiquidaPago(const INTERES: Double; const IDEMPLEADO: Integer; const IDPAGO: Integer): Boolean; }
var
  INTERES: Double;
  IDEMPLEADO: Integer;
  IDPAGO: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('INTERES', TypeInfo(Double), INTERES, []);
    __Message.Read('IDEMPLEADO', TypeInfo(Integer), IDEMPLEADO, []);
    __Message.Read('IDPAGO', TypeInfo(Integer), IDPAGO, []);

    lResult := (__Instance as IServiceGauss).LiquidaPago(INTERES, IDEMPLEADO, IDPAGO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'LiquidaPagoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_DividePago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DividePago(const idPago: Integer; const idEmpleado: Integer; const Importes: Double; const Interes: Double): Integer; }
var
  idPago: Integer;
  idEmpleado: Integer;
  Importes: Double;
  Interes: Double;
  lResult: Integer;
begin
  try
    __Message.Read('idPago', TypeInfo(Integer), idPago, []);
    __Message.Read('idEmpleado', TypeInfo(Integer), idEmpleado, []);
    __Message.Read('Importes', TypeInfo(Double), Importes, []);
    __Message.Read('Interes', TypeInfo(Double), Interes, []);

    lResult := (__Instance as IServiceGauss).DividePago(idPago, idEmpleado, Importes, Interes);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'DividePagoResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_InsertaPagoCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function InsertaPagoCaja(const IDPAGO: Integer; const IDCAJA: Integer): Boolean; }
var
  IDPAGO: Integer;
  IDCAJA: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('IDPAGO', TypeInfo(Integer), IDPAGO, []);
    __Message.Read('IDCAJA', TypeInfo(Integer), IDCAJA, []);

    lResult := (__Instance as IServiceGauss).InsertaPagoCaja(IDPAGO, IDCAJA);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'InsertaPagoCajaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_AplicaCalificacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function AplicaCalificacion(const Calificacion: Double; const Faltas: Integer; const idmaterias: Integer; const idhistorialalumno: Integer; 
                                const idhistorialgrupo: Integer; const fecha: DateTime; const idtipocalificacion: Integer; const califAux2: Double; 
                                const califAux1: Double): Boolean; }
var
  Calificacion: Double;
  Faltas: Integer;
  idmaterias: Integer;
  idhistorialalumno: Integer;
  idhistorialgrupo: Integer;
  fecha: DateTime;
  idtipocalificacion: Integer;
  califAux2: Double;
  califAux1: Double;
  lResult: Boolean;
begin
  try
    __Message.Read('Calificacion', TypeInfo(Double), Calificacion, []);
    __Message.Read('Faltas', TypeInfo(Integer), Faltas, []);
    __Message.Read('idmaterias', TypeInfo(Integer), idmaterias, []);
    __Message.Read('idhistorialalumno', TypeInfo(Integer), idhistorialalumno, []);
    __Message.Read('idhistorialgrupo', TypeInfo(Integer), idhistorialgrupo, []);
    __Message.Read('fecha', TypeInfo(DateTime), fecha, [paIsDateTime]);
    __Message.Read('idtipocalificacion', TypeInfo(Integer), idtipocalificacion, []);
    __Message.Read('califAux2', TypeInfo(Double), califAux2, []);
    __Message.Read('califAux1', TypeInfo(Double), califAux1, []);

    lResult := (__Instance as IServiceGauss).AplicaCalificacion(Calificacion, Faltas, idmaterias, idhistorialalumno, idhistorialgrupo, fecha, idtipocalificacion, califAux2, califAux1);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'AplicaCalificacionResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_HistorialAlumnoDEL(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function HistorialAlumnoDEL(const IDHISTORIALALUMNO: Integer): Boolean; }
var
  IDHISTORIALALUMNO: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('IDHISTORIALALUMNO', TypeInfo(Integer), IDHISTORIALALUMNO, []);

    lResult := (__Instance as IServiceGauss).HistorialAlumnoDEL(IDHISTORIALALUMNO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'HistorialAlumnoDELResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_BecaDescuento(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function BecaDescuento(const IDHISTORIALALUMNO: Integer; const BECA: Double; const DESCUENTO: Double): Boolean; }
var
  IDHISTORIALALUMNO: Integer;
  BECA: Double;
  DESCUENTO: Double;
  lResult: Boolean;
begin
  try
    __Message.Read('IDHISTORIALALUMNO', TypeInfo(Integer), IDHISTORIALALUMNO, []);
    __Message.Read('BECA', TypeInfo(Double), BECA, []);
    __Message.Read('DESCUENTO', TypeInfo(Double), DESCUENTO, []);

    lResult := (__Instance as IServiceGauss).BecaDescuento(IDHISTORIALALUMNO, BECA, DESCUENTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'BecaDescuentoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_InsertaHistorialAlumno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function InsertaHistorialAlumno(const IDHISTORIALALUMNO: Integer; const IDHISTORIALGRUPO: Integer; const IDALUMNO: Integer; const DOCUMENTOSFALTANTES: AnsiString; 
                                    const BECA: Double; const DESCUENTO: Double): Boolean; }
var
  IDHISTORIALALUMNO: Integer;
  IDHISTORIALGRUPO: Integer;
  IDALUMNO: Integer;
  DOCUMENTOSFALTANTES: AnsiString;
  BECA: Double;
  DESCUENTO: Double;
  lResult: Boolean;
begin
  try
    __Message.Read('IDHISTORIALALUMNO', TypeInfo(Integer), IDHISTORIALALUMNO, []);
    __Message.Read('IDHISTORIALGRUPO', TypeInfo(Integer), IDHISTORIALGRUPO, []);
    __Message.Read('IDALUMNO', TypeInfo(Integer), IDALUMNO, []);
    __Message.Read('DOCUMENTOSFALTANTES', TypeInfo(AnsiString), DOCUMENTOSFALTANTES, []);
    __Message.Read('BECA', TypeInfo(Double), BECA, []);
    __Message.Read('DESCUENTO', TypeInfo(Double), DESCUENTO, []);

    lResult := (__Instance as IServiceGauss).InsertaHistorialAlumno(IDHISTORIALALUMNO, IDHISTORIALGRUPO, IDALUMNO, DOCUMENTOSFALTANTES, BECA, DESCUENTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'InsertaHistorialAlumnoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_CambioGrupo(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function CambioGrupo(const IDHISTORIALALUMNO: Integer; const IDHISTORIALGRUPO: Integer; const DOCUMENTOSFALTANTES: AnsiString; 
                         const BECA: Double; const DESCUENTO: Double): Boolean; }
var
  IDHISTORIALALUMNO: Integer;
  IDHISTORIALGRUPO: Integer;
  DOCUMENTOSFALTANTES: AnsiString;
  BECA: Double;
  DESCUENTO: Double;
  lResult: Boolean;
begin
  try
    __Message.Read('IDHISTORIALALUMNO', TypeInfo(Integer), IDHISTORIALALUMNO, []);
    __Message.Read('IDHISTORIALGRUPO', TypeInfo(Integer), IDHISTORIALGRUPO, []);
    __Message.Read('DOCUMENTOSFALTANTES', TypeInfo(AnsiString), DOCUMENTOSFALTANTES, []);
    __Message.Read('BECA', TypeInfo(Double), BECA, []);
    __Message.Read('DESCUENTO', TypeInfo(Double), DESCUENTO, []);

    lResult := (__Instance as IServiceGauss).CambioGrupo(IDHISTORIALALUMNO, IDHISTORIALGRUPO, DOCUMENTOSFALTANTES, BECA, DESCUENTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'CambioGrupoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_TipoCalificacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function TipoCalificacion: Integer; }
var
  lResult: Integer;
begin
  try
    lResult := (__Instance as IServiceGauss).TipoCalificacion;

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'TipoCalificacionResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_DatosAlumno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DatosAlumno(const AlumnoID: Integer): TDatos; }
var
  AlumnoID: Integer;
  lResult: LibraryGauss_Intf.TDatos;
  __lObjectDisposer: TROObjectDisposer;
begin
  lResult := nil;
  try
    __Message.Read('AlumnoID', TypeInfo(Integer), AlumnoID, []);

    lResult := (__Instance as IServiceGauss).DatosAlumno(AlumnoID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'DatosAlumnoResponse');
    __Message.Write('Result', TypeInfo(LibraryGauss_Intf.TDatos), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceGauss_Invoker.Invoke_DatosMaestro(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DatosMaestro(const MaestroID: Integer): TDatos; }
var
  MaestroID: Integer;
  lResult: LibraryGauss_Intf.TDatos;
  __lObjectDisposer: TROObjectDisposer;
begin
  lResult := nil;
  try
    __Message.Read('MaestroID', TypeInfo(Integer), MaestroID, []);

    lResult := (__Instance as IServiceGauss).DatosMaestro(MaestroID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'DatosMaestroResponse');
    __Message.Write('Result', TypeInfo(LibraryGauss_Intf.TDatos), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceGauss_Invoker.Invoke_PagoBanco(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function PagoBanco(const FECHAPAGO: DateTime; const IDEMPLEADO: Integer; const IDPAGO: Integer; const MONTO: Double): Integer; }
var
  FECHAPAGO: DateTime;
  IDEMPLEADO: Integer;
  IDPAGO: Integer;
  MONTO: Double;
  lResult: Integer;
begin
  try
    __Message.Read('FECHAPAGO', TypeInfo(DateTime), FECHAPAGO, [paIsDateTime]);
    __Message.Read('IDEMPLEADO', TypeInfo(Integer), IDEMPLEADO, []);
    __Message.Read('IDPAGO', TypeInfo(Integer), IDPAGO, []);
    __Message.Read('MONTO', TypeInfo(Double), MONTO, []);

    lResult := (__Instance as IServiceGauss).PagoBanco(FECHAPAGO, IDEMPLEADO, IDPAGO, MONTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'PagoBancoResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_PrecioProducto(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function PrecioProducto(const ProductoID: Integer): Double; }
var
  ProductoID: Integer;
  lResult: Double;
begin
  try
    __Message.Read('ProductoID', TypeInfo(Integer), ProductoID, []);

    lResult := (__Instance as IServiceGauss).PrecioProducto(ProductoID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'PrecioProductoResponse');
    __Message.Write('Result', TypeInfo(Double), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_FolioActual(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function FolioActual(const Campo: AnsiString; const Serie: AnsiString): Integer; }
var
  Campo: AnsiString;
  Serie: AnsiString;
  lResult: Integer;
begin
  try
    __Message.Read('Campo', TypeInfo(AnsiString), Campo, []);
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);

    lResult := (__Instance as IServiceGauss).FolioActual(Campo, Serie);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'FolioActualResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_ValidaFolioFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ValidaFolioFactura(const Campo: AnsiString; const Folio: Integer): Boolean; }
var
  Campo: AnsiString;
  Folio: Integer;
  lResult: Boolean;
begin
  try
    __Message.Read('Campo', TypeInfo(AnsiString), Campo, []);
    __Message.Read('Folio', TypeInfo(Integer), Folio, []);

    lResult := (__Instance as IServiceGauss).ValidaFolioFactura(Campo, Folio);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'ValidaFolioFacturaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceGauss_Invoker.Invoke_GuardarDatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ procedure GuardarDatosFactura(const DatosFactura: TDatosFactura); }
var
  DatosFactura: LibraryGauss_Intf.TDatosFactura;
  __lObjectDisposer: TROObjectDisposer;
begin
  DatosFactura := nil;
  try
    __Message.Read('DatosFactura', TypeInfo(LibraryGauss_Intf.TDatosFactura), DatosFactura, []);

    (__Instance as IServiceGauss).GuardarDatosFactura(DatosFactura);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'GuardarDatosFacturaResponse');
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

    __oResponseOptions := [roNoResponse];

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(DatosFactura);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceGauss_Invoker.Invoke_CadenaOriginal(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function CadenaOriginal(const FacturaID: Integer): TDataFacturaElectronicaF; }
var
  FacturaID: Integer;
  lResult: LibraryGauss_Intf.TDataFacturaElectronicaF;
  __lObjectDisposer: TROObjectDisposer;
begin
  lResult := nil;
  try
    __Message.Read('FacturaID', TypeInfo(Integer), FacturaID, []);

    lResult := (__Instance as IServiceGauss).CadenaOriginal(FacturaID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryGauss', 'ServiceGauss', 'CadenaOriginalResponse');
    __Message.Write('Result', TypeInfo(LibraryGauss_Intf.TDataFacturaElectronicaF), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

initialization
end.
