unit LibraryIngresos_Invk;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes,
  {RemObjects:} uROXMLIntf, uROServer, uROServerIntf, uROClasses, uROTypes, uROClientIntf,
  {Used RODL Intf's:} DataAbstract4_Intf,
  {Used RODL Invk's:} DataAbstract4_Invk,
  {Generated:} LibraryIngresos_Intf;

type
  TSeekOrigin = Classes.TSeekOrigin; // fake declaration
  TServiceIngresos_Invoker = class(TDataAbstractService_Invoker)
  private
  protected
  public
    constructor Create; override;
  published
    procedure Invoke_AbreDataSetReportes(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_AbreTurno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ObtenTurnosdeFecha(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_BuscarReporte(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DragPagoMateria(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ActualizaSubTipoPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DatosFacturaElectronica(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_Fecha(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_Folio(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_GuardaDatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_Login(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_IniciaCiclo(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ModificarFolioActual(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_InsertaFacturaElectronica(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_FolioActual2(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_GuardaAccesos(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_EliminaMaestroDisponibilidad(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_EliminaMateriaMaestro(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_EliminaPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_EliminaPagoCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_InsertaCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_LiquidaPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DividePago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_InsertaPagoCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_AplicaCalificacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_HistorialAlumnoDEL(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_BecaDescuento(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_InsertaHistorialAlumno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_CambioGrupo(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_TipoCalificacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DatosAlumno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_DatosMaestro(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_PagoBanco(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_PrecioProducto(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_FolioActual(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ValidaFolioFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_GuardarDatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ActualizaTipoCampio(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_ObtenTipoValores(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_CostoProducto(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_Exporta(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_CierraLiquidacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_comboestacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_comboscompras(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
    procedure Invoke_IANcomprasGuarda(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
  end;

implementation

uses
  {RemObjects:} uRORes, uROClient;

{ TServiceIngresos_Invoker }

constructor TServiceIngresos_Invoker.Create;
begin
  inherited Create;
  FAbstract := False;
end;

procedure TServiceIngresos_Invoker.Invoke_AbreDataSetReportes(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function AbreDataSetReportes(const SQL: AnsiString; const Parametros: TParametrosBI): Binary; }
var
  SQL: AnsiString;
  Parametros: LibraryIngresos_Intf.TParametrosBI;
  lResult: Binary;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  Parametros := nil;
  lResult := nil;
  try
    __Message.Read('SQL', TypeInfo(AnsiString), SQL, []);
    __Message.Read('Parametros', TypeInfo(LibraryIngresos_Intf.TParametrosBI), Parametros, []);

    lResult := (__Instance as IServiceIngresos).AbreDataSetReportes(SQL, Parametros);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'AbreDataSetReportesResponse');
    __Message.Write('Result', TypeInfo(Binary), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(Parametros);
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_AbreTurno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function AbreTurno(const IDTURNO: Integer; const IDESTACION: Integer; const FECHA: DateTime): AnsiString; }
var
  IDTURNO: Integer;
  IDESTACION: Integer;
  FECHA: DateTime;
  lResult: AnsiString;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDTURNO', TypeInfo(Integer), IDTURNO, []);
    __Message.Read('IDESTACION', TypeInfo(Integer), IDESTACION, []);
    __Message.Read('FECHA', TypeInfo(DateTime), FECHA, [paIsDateTime]);

    lResult := (__Instance as IServiceIngresos).AbreTurno(IDTURNO, IDESTACION, FECHA);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'AbreTurnoResponse');
    __Message.Write('Result', TypeInfo(AnsiString), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_ObtenTurnosdeFecha(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ObtenTurnosdeFecha(const Fecha: DateTime; const Estacion: Integer): ATTurnoxFecha; }
var
  Fecha: DateTime;
  Estacion: Integer;
  lResult: LibraryIngresos_Intf.ATTurnoxFecha;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  lResult := nil;
  try
    __Message.Read('Fecha', TypeInfo(DateTime), Fecha, [paIsDateTime]);
    __Message.Read('Estacion', TypeInfo(Integer), Estacion, []);

    lResult := (__Instance as IServiceIngresos).ObtenTurnosdeFecha(Fecha, Estacion);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'ObtenTurnosdeFechaResponse');
    __Message.Write('Result', TypeInfo(LibraryIngresos_Intf.ATTurnoxFecha), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_BuscarReporte(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function BuscarReporte(const Nombre: AnsiString): TReporteBI; }
var
  Nombre: AnsiString;
  lResult: LibraryIngresos_Intf.TReporteBI;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  lResult := nil;
  try
    __Message.Read('Nombre', TypeInfo(AnsiString), Nombre, []);

    lResult := (__Instance as IServiceIngresos).BuscarReporte(Nombre);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'BuscarReporteResponse');
    __Message.Write('Result', TypeInfo(LibraryIngresos_Intf.TReporteBI), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_DragPagoMateria(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DragPagoMateria(const PAGOMATERIA: Integer; const IDGRUPOTARGET: Integer; const IDGRUPOSOURCE: Integer): Boolean; }
var
  PAGOMATERIA: Integer;
  IDGRUPOTARGET: Integer;
  IDGRUPOSOURCE: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('PAGOMATERIA', TypeInfo(Integer), PAGOMATERIA, []);
    __Message.Read('IDGRUPOTARGET', TypeInfo(Integer), IDGRUPOTARGET, []);
    __Message.Read('IDGRUPOSOURCE', TypeInfo(Integer), IDGRUPOSOURCE, []);

    lResult := (__Instance as IServiceIngresos).DragPagoMateria(PAGOMATERIA, IDGRUPOTARGET, IDGRUPOSOURCE);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'DragPagoMateriaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_ActualizaSubTipoPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ActualizaSubTipoPago(const IDTIPOPAGO: Integer; const IDSUBTIPOPAGO: Integer): Boolean; }
var
  IDTIPOPAGO: Integer;
  IDSUBTIPOPAGO: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDTIPOPAGO', TypeInfo(Integer), IDTIPOPAGO, []);
    __Message.Read('IDSUBTIPOPAGO', TypeInfo(Integer), IDSUBTIPOPAGO, []);

    lResult := (__Instance as IServiceIngresos).ActualizaSubTipoPago(IDTIPOPAGO, IDSUBTIPOPAGO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'ActualizaSubTipoPagoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_DatosFacturaElectronica(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DatosFacturaElectronica(const FacturaID: Integer; const NumeroEstacion: Integer): TFacturaElectronicaBI; }
var
  FacturaID: Integer;
  NumeroEstacion: Integer;
  lResult: LibraryIngresos_Intf.TFacturaElectronicaBI;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  lResult := nil;
  try
    __Message.Read('FacturaID', TypeInfo(Integer), FacturaID, []);
    __Message.Read('NumeroEstacion', TypeInfo(Integer), NumeroEstacion, []);

    lResult := (__Instance as IServiceIngresos).DatosFacturaElectronica(FacturaID, NumeroEstacion);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'DatosFacturaElectronicaResponse');
    __Message.Write('Result', TypeInfo(LibraryIngresos_Intf.TFacturaElectronicaBI), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_DatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DatosFactura(const Folio: Integer; const Serie: AnsiString): Boolean; }
var
  Folio: Integer;
  Serie: AnsiString;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('Folio', TypeInfo(Integer), Folio, []);
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);

    lResult := (__Instance as IServiceIngresos).DatosFactura(Folio, Serie);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'DatosFacturaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_Fecha(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function Fecha: DateTime; }
var
  lResult: DateTime;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    lResult := (__Instance as IServiceIngresos).Fecha;

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'FechaResponse');
    __Message.Write('Result', TypeInfo(DateTime), lResult, [paIsDateTime]);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_Folio(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function Folio(const Campo: AnsiString; const Serie: AnsiString): Integer; }
var
  Campo: AnsiString;
  Serie: AnsiString;
  lResult: Integer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('Campo', TypeInfo(AnsiString), Campo, []);
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);

    lResult := (__Instance as IServiceIngresos).Folio(Campo, Serie);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'FolioResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_GuardaDatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ procedure GuardaDatosFactura(const DatosFactura: TDatosFactura); }
var
  DatosFactura: LibraryIngresos_Intf.TDatosFactura;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  DatosFactura := nil;
  try
    __Message.Read('DatosFactura', TypeInfo(LibraryIngresos_Intf.TDatosFactura), DatosFactura, []);

    (__Instance as IServiceIngresos).GuardaDatosFactura(DatosFactura);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'GuardaDatosFacturaResponse');
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

    __oResponseOptions := [roNoResponse];

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(DatosFactura);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_Login(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function Login(const Usuario: AnsiString; const Clave: AnsiString): TLoginInfoBI; }
var
  Usuario: AnsiString;
  Clave: AnsiString;
  lResult: LibraryIngresos_Intf.TLoginInfoBI;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  lResult := nil;
  try
    __Message.Read('Usuario', TypeInfo(AnsiString), Usuario, []);
    __Message.Read('Clave', TypeInfo(AnsiString), Clave, []);

    lResult := (__Instance as IServiceIngresos).Login(Usuario, Clave);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'LoginResponse');
    __Message.Write('Result', TypeInfo(LibraryIngresos_Intf.TLoginInfoBI), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_IniciaCiclo(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function IniciaCiclo(const IDCICLO: AnsiString): Boolean; }
var
  IDCICLO: AnsiString;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDCICLO', TypeInfo(AnsiString), IDCICLO, []);

    lResult := (__Instance as IServiceIngresos).IniciaCiclo(IDCICLO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'IniciaCicloResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_ModificarFolioActual(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ModificarFolioActual(const Campo: AnsiString; const Serie: AnsiString; const FolioNew: Integer): AnsiString; }
var
  Campo: AnsiString;
  Serie: AnsiString;
  FolioNew: Integer;
  lResult: AnsiString;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('Campo', TypeInfo(AnsiString), Campo, []);
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);
    __Message.Read('FolioNew', TypeInfo(Integer), FolioNew, []);

    lResult := (__Instance as IServiceIngresos).ModificarFolioActual(Campo, Serie, FolioNew);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'ModificarFolioActualResponse');
    __Message.Write('Result', TypeInfo(AnsiString), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_InsertaFacturaElectronica(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ procedure InsertaFacturaElectronica(const FacturaElectronicaID: Integer; const CadenaOriginal: UnicodeString; const SelloDigital: UnicodeString;
                                        const FacturaID: Integer; const Vigencia: Boolean; const Enviado: Boolean; const NoCertificado: AnsiString;
                                        const NoAprobacion: AnsiString; const FechaAprobacion: DateTime; const XMLCFD: UnicodeString; const XMLCFDI: UnicodeString); }
var
  FacturaElectronicaID: Integer;
  CadenaOriginal: UnicodeString;
  SelloDigital: UnicodeString;
  FacturaID: Integer;
  Vigencia: Boolean;
  Enviado: Boolean;
  NoCertificado: AnsiString;
  NoAprobacion: AnsiString;
  FechaAprobacion: DateTime;
  XMLCFD: UnicodeString;
  XMLCFDI: UnicodeString;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('FacturaElectronicaID', TypeInfo(Integer), FacturaElectronicaID, []);
    __Message.Read('CadenaOriginal', TypeInfo(UnicodeString), CadenaOriginal, []);
    __Message.Read('SelloDigital', TypeInfo(UnicodeString), SelloDigital, []);
    __Message.Read('FacturaID', TypeInfo(Integer), FacturaID, []);
    __Message.Read('Vigencia', TypeInfo(Boolean), Vigencia, []);
    __Message.Read('Enviado', TypeInfo(Boolean), Enviado, []);
    __Message.Read('NoCertificado', TypeInfo(AnsiString), NoCertificado, []);
    __Message.Read('NoAprobacion', TypeInfo(AnsiString), NoAprobacion, []);
    __Message.Read('FechaAprobacion', TypeInfo(DateTime), FechaAprobacion, [paIsDateTime]);
    __Message.Read('XMLCFD', TypeInfo(UnicodeString), XMLCFD, []);
    __Message.Read('XMLCFDI', TypeInfo(UnicodeString), XMLCFDI, []);

    (__Instance as IServiceIngresos).InsertaFacturaElectronica(FacturaElectronicaID, CadenaOriginal, SelloDigital, FacturaID, Vigencia, Enviado, NoCertificado,
        NoAprobacion, FechaAprobacion, XMLCFD, XMLCFDI);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'InsertaFacturaElectronicaResponse');
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

    __oResponseOptions := [roNoResponse];

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_FolioActual2(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function FolioActual2(const Serie: AnsiString; const folio: Integer): Integer; }
var
  Serie: AnsiString;
  folio: Integer;
  lResult: Integer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);
    __Message.Read('folio', TypeInfo(Integer), folio, []);

    lResult := (__Instance as IServiceIngresos).FolioActual2(Serie, folio);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'FolioActual2Response');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_GuardaAccesos(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ procedure GuardaAccesos(const UsuarioID: Integer; const Lista: AnsiString); }
var
  UsuarioID: Integer;
  Lista: AnsiString;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('UsuarioID', TypeInfo(Integer), UsuarioID, []);
    __Message.Read('Lista', TypeInfo(AnsiString), Lista, []);

    (__Instance as IServiceIngresos).GuardaAccesos(UsuarioID, Lista);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'GuardaAccesosResponse');
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

    __oResponseOptions := [roNoResponse];

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_EliminaMaestroDisponibilidad(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function EliminaMaestroDisponibilidad(const IDMAESTRODISPONIBILIDAD: Integer): Boolean; }
var
  IDMAESTRODISPONIBILIDAD: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDMAESTRODISPONIBILIDAD', TypeInfo(Integer), IDMAESTRODISPONIBILIDAD, []);

    lResult := (__Instance as IServiceIngresos).EliminaMaestroDisponibilidad(IDMAESTRODISPONIBILIDAD);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'EliminaMaestroDisponibilidadResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_EliminaMateriaMaestro(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function EliminaMateriaMaestro(const IDMAESTRO: Integer; const IDMATERIA: Integer): Boolean; }
var
  IDMAESTRO: Integer;
  IDMATERIA: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDMAESTRO', TypeInfo(Integer), IDMAESTRO, []);
    __Message.Read('IDMATERIA', TypeInfo(Integer), IDMATERIA, []);

    lResult := (__Instance as IServiceIngresos).EliminaMateriaMaestro(IDMAESTRO, IDMATERIA);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'EliminaMateriaMaestroResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_EliminaPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function EliminaPago(const idSubtipoPago: Integer; const status: AnsiString; const idCiclos: Integer; const idGrupo: Integer): Boolean; }
var
  idSubtipoPago: Integer;
  status: AnsiString;
  idCiclos: Integer;
  idGrupo: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('idSubtipoPago', TypeInfo(Integer), idSubtipoPago, []);
    __Message.Read('status', TypeInfo(AnsiString), status, []);
    __Message.Read('idCiclos', TypeInfo(Integer), idCiclos, []);
    __Message.Read('idGrupo', TypeInfo(Integer), idGrupo, []);

    lResult := (__Instance as IServiceIngresos).EliminaPago(idSubtipoPago, status, idCiclos, idGrupo);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'EliminaPagoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_EliminaPagoCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function EliminaPagoCaja(const idSubtipoPago: Integer; const status: AnsiString; const idCiclos: Integer; const idGrupo: Integer): Boolean; }
var
  idSubtipoPago: Integer;
  status: AnsiString;
  idCiclos: Integer;
  idGrupo: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('idSubtipoPago', TypeInfo(Integer), idSubtipoPago, []);
    __Message.Read('status', TypeInfo(AnsiString), status, []);
    __Message.Read('idCiclos', TypeInfo(Integer), idCiclos, []);
    __Message.Read('idGrupo', TypeInfo(Integer), idGrupo, []);

    lResult := (__Instance as IServiceIngresos).EliminaPagoCaja(idSubtipoPago, status, idCiclos, idGrupo);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'EliminaPagoCajaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_InsertaCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function InsertaCaja(const Observaciones: AnsiString; const TipoPago: AnsiString; const idEmpleado: Integer): Integer; }
var
  Observaciones: AnsiString;
  TipoPago: AnsiString;
  idEmpleado: Integer;
  lResult: Integer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('Observaciones', TypeInfo(AnsiString), Observaciones, []);
    __Message.Read('TipoPago', TypeInfo(AnsiString), TipoPago, []);
    __Message.Read('idEmpleado', TypeInfo(Integer), idEmpleado, []);

    lResult := (__Instance as IServiceIngresos).InsertaCaja(Observaciones, TipoPago, idEmpleado);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'InsertaCajaResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_LiquidaPago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function LiquidaPago(const INTERES: Double; const IDEMPLEADO: Integer; const IDPAGO: Integer): Boolean; }
var
  INTERES: Double;
  IDEMPLEADO: Integer;
  IDPAGO: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('INTERES', TypeInfo(Double), INTERES, []);
    __Message.Read('IDEMPLEADO', TypeInfo(Integer), IDEMPLEADO, []);
    __Message.Read('IDPAGO', TypeInfo(Integer), IDPAGO, []);

    lResult := (__Instance as IServiceIngresos).LiquidaPago(INTERES, IDEMPLEADO, IDPAGO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'LiquidaPagoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_DividePago(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DividePago(const idPago: Integer; const idEmpleado: Integer; const Importes: Double; const Interes: Double): Integer; }
var
  idPago: Integer;
  idEmpleado: Integer;
  Importes: Double;
  Interes: Double;
  lResult: Integer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('idPago', TypeInfo(Integer), idPago, []);
    __Message.Read('idEmpleado', TypeInfo(Integer), idEmpleado, []);
    __Message.Read('Importes', TypeInfo(Double), Importes, []);
    __Message.Read('Interes', TypeInfo(Double), Interes, []);

    lResult := (__Instance as IServiceIngresos).DividePago(idPago, idEmpleado, Importes, Interes);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'DividePagoResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_InsertaPagoCaja(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function InsertaPagoCaja(const IDPAGO: Integer; const IDCAJA: Integer): Boolean; }
var
  IDPAGO: Integer;
  IDCAJA: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDPAGO', TypeInfo(Integer), IDPAGO, []);
    __Message.Read('IDCAJA', TypeInfo(Integer), IDCAJA, []);

    lResult := (__Instance as IServiceIngresos).InsertaPagoCaja(IDPAGO, IDCAJA);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'InsertaPagoCajaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_AplicaCalificacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function AplicaCalificacion(const Calificacion: Double; const Faltas: Integer; const idmaterias: Integer; const idhistorialalumno: Integer;
                                const idhistorialgrupo: Integer; const fecha: DateTime; const idtipocalificacion: Integer; const califAux2: Double;
                                const califAux1: Double): Boolean; }
var
  Calificacion: Double;
  Faltas: Integer;
  idmaterias: Integer;
  idhistorialalumno: Integer;
  idhistorialgrupo: Integer;
  fecha: DateTime;
  idtipocalificacion: Integer;
  califAux2: Double;
  califAux1: Double;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('Calificacion', TypeInfo(Double), Calificacion, []);
    __Message.Read('Faltas', TypeInfo(Integer), Faltas, []);
    __Message.Read('idmaterias', TypeInfo(Integer), idmaterias, []);
    __Message.Read('idhistorialalumno', TypeInfo(Integer), idhistorialalumno, []);
    __Message.Read('idhistorialgrupo', TypeInfo(Integer), idhistorialgrupo, []);
    __Message.Read('fecha', TypeInfo(DateTime), fecha, [paIsDateTime]);
    __Message.Read('idtipocalificacion', TypeInfo(Integer), idtipocalificacion, []);
    __Message.Read('califAux2', TypeInfo(Double), califAux2, []);
    __Message.Read('califAux1', TypeInfo(Double), califAux1, []);

    lResult := (__Instance as IServiceIngresos).AplicaCalificacion(Calificacion, Faltas, idmaterias, idhistorialalumno, idhistorialgrupo, fecha, idtipocalificacion,
        califAux2, califAux1);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'AplicaCalificacionResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_HistorialAlumnoDEL(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function HistorialAlumnoDEL(const IDHISTORIALALUMNO: Integer): Boolean; }
var
  IDHISTORIALALUMNO: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDHISTORIALALUMNO', TypeInfo(Integer), IDHISTORIALALUMNO, []);

    lResult := (__Instance as IServiceIngresos).HistorialAlumnoDEL(IDHISTORIALALUMNO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'HistorialAlumnoDELResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_BecaDescuento(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function BecaDescuento(const IDHISTORIALALUMNO: Integer; const BECA: Double; const DESCUENTO: Double): Boolean; }
var
  IDHISTORIALALUMNO: Integer;
  BECA: Double;
  DESCUENTO: Double;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDHISTORIALALUMNO', TypeInfo(Integer), IDHISTORIALALUMNO, []);
    __Message.Read('BECA', TypeInfo(Double), BECA, []);
    __Message.Read('DESCUENTO', TypeInfo(Double), DESCUENTO, []);

    lResult := (__Instance as IServiceIngresos).BecaDescuento(IDHISTORIALALUMNO, BECA, DESCUENTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'BecaDescuentoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_InsertaHistorialAlumno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function InsertaHistorialAlumno(const IDHISTORIALALUMNO: Integer; const IDHISTORIALGRUPO: Integer; const IDALUMNO: Integer; const DOCUMENTOSFALTANTES: AnsiString;
                                    const BECA: Double; const DESCUENTO: Double): Boolean; }
var
  IDHISTORIALALUMNO: Integer;
  IDHISTORIALGRUPO: Integer;
  IDALUMNO: Integer;
  DOCUMENTOSFALTANTES: AnsiString;
  BECA: Double;
  DESCUENTO: Double;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDHISTORIALALUMNO', TypeInfo(Integer), IDHISTORIALALUMNO, []);
    __Message.Read('IDHISTORIALGRUPO', TypeInfo(Integer), IDHISTORIALGRUPO, []);
    __Message.Read('IDALUMNO', TypeInfo(Integer), IDALUMNO, []);
    __Message.Read('DOCUMENTOSFALTANTES', TypeInfo(AnsiString), DOCUMENTOSFALTANTES, []);
    __Message.Read('BECA', TypeInfo(Double), BECA, []);
    __Message.Read('DESCUENTO', TypeInfo(Double), DESCUENTO, []);

    lResult := (__Instance as IServiceIngresos).InsertaHistorialAlumno(IDHISTORIALALUMNO, IDHISTORIALGRUPO, IDALUMNO, DOCUMENTOSFALTANTES, BECA, DESCUENTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'InsertaHistorialAlumnoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_CambioGrupo(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function CambioGrupo(const IDHISTORIALALUMNO: Integer; const IDHISTORIALGRUPO: Integer; const DOCUMENTOSFALTANTES: AnsiString;
                         const BECA: Double; const DESCUENTO: Double): Boolean; }
var
  IDHISTORIALALUMNO: Integer;
  IDHISTORIALGRUPO: Integer;
  DOCUMENTOSFALTANTES: AnsiString;
  BECA: Double;
  DESCUENTO: Double;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDHISTORIALALUMNO', TypeInfo(Integer), IDHISTORIALALUMNO, []);
    __Message.Read('IDHISTORIALGRUPO', TypeInfo(Integer), IDHISTORIALGRUPO, []);
    __Message.Read('DOCUMENTOSFALTANTES', TypeInfo(AnsiString), DOCUMENTOSFALTANTES, []);
    __Message.Read('BECA', TypeInfo(Double), BECA, []);
    __Message.Read('DESCUENTO', TypeInfo(Double), DESCUENTO, []);

    lResult := (__Instance as IServiceIngresos).CambioGrupo(IDHISTORIALALUMNO, IDHISTORIALGRUPO, DOCUMENTOSFALTANTES, BECA, DESCUENTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'CambioGrupoResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_TipoCalificacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function TipoCalificacion: Integer; }
var
  lResult: Integer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    lResult := (__Instance as IServiceIngresos).TipoCalificacion;

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'TipoCalificacionResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_DatosAlumno(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DatosAlumno(const AlumnoID: Integer): TDatos; }
var
  AlumnoID: Integer;
  lResult: LibraryIngresos_Intf.TDatos;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  lResult := nil;
  try
    __Message.Read('AlumnoID', TypeInfo(Integer), AlumnoID, []);

    lResult := (__Instance as IServiceIngresos).DatosAlumno(AlumnoID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'DatosAlumnoResponse');
    __Message.Write('Result', TypeInfo(LibraryIngresos_Intf.TDatos), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_DatosMaestro(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function DatosMaestro(const MaestroID: Integer): TDatos; }
var
  MaestroID: Integer;
  lResult: LibraryIngresos_Intf.TDatos;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  lResult := nil;
  try
    __Message.Read('MaestroID', TypeInfo(Integer), MaestroID, []);

    lResult := (__Instance as IServiceIngresos).DatosMaestro(MaestroID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'DatosMaestroResponse');
    __Message.Write('Result', TypeInfo(LibraryIngresos_Intf.TDatos), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_PagoBanco(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function PagoBanco(const FECHAPAGO: DateTime; const IDEMPLEADO: Integer; const IDPAGO: Integer; const MONTO: Double): Integer; }
var
  FECHAPAGO: DateTime;
  IDEMPLEADO: Integer;
  IDPAGO: Integer;
  MONTO: Double;
  lResult: Integer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('FECHAPAGO', TypeInfo(DateTime), FECHAPAGO, [paIsDateTime]);
    __Message.Read('IDEMPLEADO', TypeInfo(Integer), IDEMPLEADO, []);
    __Message.Read('IDPAGO', TypeInfo(Integer), IDPAGO, []);
    __Message.Read('MONTO', TypeInfo(Double), MONTO, []);

    lResult := (__Instance as IServiceIngresos).PagoBanco(FECHAPAGO, IDEMPLEADO, IDPAGO, MONTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'PagoBancoResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_PrecioProducto(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function PrecioProducto(const ProductoID: Integer): Double; }
var
  ProductoID: Integer;
  lResult: Double;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('ProductoID', TypeInfo(Integer), ProductoID, []);

    lResult := (__Instance as IServiceIngresos).PrecioProducto(ProductoID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'PrecioProductoResponse');
    __Message.Write('Result', TypeInfo(Double), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_FolioActual(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function FolioActual(const Campo: AnsiString; const Serie: AnsiString): Integer; }
var
  Campo: AnsiString;
  Serie: AnsiString;
  lResult: Integer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('Campo', TypeInfo(AnsiString), Campo, []);
    __Message.Read('Serie', TypeInfo(AnsiString), Serie, []);

    lResult := (__Instance as IServiceIngresos).FolioActual(Campo, Serie);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'FolioActualResponse');
    __Message.Write('Result', TypeInfo(Integer), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_ValidaFolioFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ValidaFolioFactura(const Campo: AnsiString; const Folio: Integer): Boolean; }
var
  Campo: AnsiString;
  Folio: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('Campo', TypeInfo(AnsiString), Campo, []);
    __Message.Read('Folio', TypeInfo(Integer), Folio, []);

    lResult := (__Instance as IServiceIngresos).ValidaFolioFactura(Campo, Folio);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'ValidaFolioFacturaResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_GuardarDatosFactura(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function GuardarDatosFactura(const DatosFactura: TDatosFactura): AnsiString; }
var
  DatosFactura: LibraryIngresos_Intf.TDatosFactura;
  lResult: AnsiString;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  DatosFactura := nil;
  try
    __Message.Read('DatosFactura', TypeInfo(LibraryIngresos_Intf.TDatosFactura), DatosFactura, []);

    lResult := (__Instance as IServiceIngresos).GuardarDatosFactura(DatosFactura);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'GuardarDatosFacturaResponse');
    __Message.Write('Result', TypeInfo(AnsiString), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(DatosFactura);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_ActualizaTipoCampio(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ActualizaTipoCampio(const NUMEROESTACION: Int64; const FECHA: DateTime; const VALOR: Double; const IDMONEDA: Integer): Boolean; }
var
  NUMEROESTACION: Int64;
  FECHA: DateTime;
  VALOR: Double;
  IDMONEDA: Integer;
  lResult: Boolean;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('NUMEROESTACION', TypeInfo(Int64), NUMEROESTACION, []);
    __Message.Read('FECHA', TypeInfo(DateTime), FECHA, [paIsDateTime]);
    __Message.Read('VALOR', TypeInfo(Double), VALOR, []);
    __Message.Read('IDMONEDA', TypeInfo(Integer), IDMONEDA, []);

    lResult := (__Instance as IServiceIngresos).ActualizaTipoCampio(NUMEROESTACION, FECHA, VALOR, IDMONEDA);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'ActualizaTipoCampioResponse');
    __Message.Write('Result', TypeInfo(Boolean), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_ObtenTipoValores(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function ObtenTipoValores(const NUMEROESTACION: Integer; const FECHA: DateTime): ATTipoValores; }
var
  NUMEROESTACION: Integer;
  FECHA: DateTime;
  lResult: LibraryIngresos_Intf.ATTipoValores;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  lResult := nil;
  try
    __Message.Read('NUMEROESTACION', TypeInfo(Integer), NUMEROESTACION, []);
    __Message.Read('FECHA', TypeInfo(DateTime), FECHA, [paIsDateTime]);

    lResult := (__Instance as IServiceIngresos).ObtenTipoValores(NUMEROESTACION, FECHA);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'ObtenTipoValoresResponse');
    __Message.Write('Result', TypeInfo(LibraryIngresos_Intf.ATTipoValores), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_CostoProducto(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function CostoProducto(const IDPRODUCTO: Integer): Double; }
var
  IDPRODUCTO: Integer;
  lResult: Double;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('IDPRODUCTO', TypeInfo(Integer), IDPRODUCTO, []);

    lResult := (__Instance as IServiceIngresos).CostoProducto(IDPRODUCTO);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'CostoProductoResponse');
    __Message.Write('Result', TypeInfo(Double), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_Exporta(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function Exporta(const ExportarID: Integer): TExporta; }
var
  ExportarID: Integer;
  lResult: LibraryIngresos_Intf.TExporta;
  __lObjectDisposer: TROObjectDisposer;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  lResult := nil;
  try
    __Message.Read('ExportarID', TypeInfo(Integer), ExportarID, []);

    lResult := (__Instance as IServiceIngresos).Exporta(ExportarID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'ExportaResponse');
    __Message.Write('Result', TypeInfo(LibraryIngresos_Intf.TExporta), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
    __lObjectDisposer := TROObjectDisposer.Create(__Instance);
    try
      __lObjectDisposer.Add(lResult);
    finally
      __lObjectDisposer.Free();
    end;
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_CierraLiquidacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function CierraLiquidacion(const LiquidacionID: Integer): AnsiString; }
var
  LiquidacionID: Integer;
  lResult: AnsiString;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('LiquidacionID', TypeInfo(Integer), LiquidacionID, []);

    lResult := (__Instance as IServiceIngresos).CierraLiquidacion(LiquidacionID);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'CierraLiquidacionResponse');
    __Message.Write('Result', TypeInfo(AnsiString), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_comboestacion(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function comboestacion(const estacionid: AnsiString): AnsiString; }
var
  estacionid: AnsiString;
  lResult: AnsiString;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('estacionid', TypeInfo(AnsiString), estacionid, []);

    lResult := (__Instance as IServiceIngresos).comboestacion(estacionid);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'comboestacionResponse');
    __Message.Write('Result', TypeInfo(AnsiString), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_comboscompras(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function comboscompras(const estacionid: AnsiString): AnsiString; }
var
  estacionid: AnsiString;
  lResult: AnsiString;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('estacionid', TypeInfo(AnsiString), estacionid, []);

    lResult := (__Instance as IServiceIngresos).comboscompras(estacionid);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'comboscomprasResponse');
    __Message.Write('Result', TypeInfo(AnsiString), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

procedure TServiceIngresos_Invoker.Invoke_IANcomprasGuarda(const __Instance:IInterface; const __Message:IROMessage; const __Transport:IROTransport; out __oResponseOptions:TROResponseOptions);
{ function IANcomprasGuarda(const MovimientoAlmacenMaestro: AnsiString; const MovimientoAlmacenDetalle: AnsiString): AnsiString; }
var
  MovimientoAlmacenMaestro: AnsiString;
  MovimientoAlmacenDetalle: AnsiString;
  lResult: AnsiString;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles);
  try
    __Message.Read('MovimientoAlmacenMaestro', TypeInfo(AnsiString), MovimientoAlmacenMaestro, []);
    __Message.Read('MovimientoAlmacenDetalle', TypeInfo(AnsiString), MovimientoAlmacenDetalle, []);

    lResult := (__Instance as IServiceIngresos).IANcomprasGuarda(MovimientoAlmacenMaestro, MovimientoAlmacenDetalle);

    __Message.InitializeResponseMessage(__Transport, 'LibraryIngresos', 'ServiceIngresos', 'IANcomprasGuardaResponse');
    __Message.Write('Result', TypeInfo(AnsiString), lResult, []);
    __Message.Finalize;
    __Message.UnsetAttributes(__Transport);

  finally
  end;
end;

initialization
end.
